### ISSUE TITLE
unitypackage作成高速化の提案

### ISSUE THREAD

**Issue by pCYSl5EDgo** [hadashiA/VContainer#1]
手前味噌ではございますが、 https://github.com/pCYSl5EDgo/create-unitypackage というGitHub Actionを利用しますとGableroux氏のDockerコンテナを使用する場合よりも高速にunitypackageを生成できます。

**Comment by hadashiA** [comment]
@pCYSl5EDgo 
ははー  unitypackage作成を自前で実装されてるんですか。

実は現状、DockerでのUnityがうまく走ってなかったので、、使わせてもらおうかなと思ったのですが、

試してみたところ、↓のような問題に見舞われてしまい、リポジトリの方にIssueで報告させてもらいました。
https://github.com/pCYSl5EDgo/create-unitypackage/issues/1

**Comment by hadashiA** [comment]
@pCYSl5EDgo 

リポジトリの方にもコメントさせてもらったんですが、おそらく、問題は upload-artifact がフォーマットを変更することにありそうだと思ってます 🤔 

- VContainer.unitypackage を uploadする → VContainer.unitypackage.zip がアップロードされ、勝手にzip圧縮されている。
    - これを macOS で `VContainer.unitypackage` にリネームしてみる →  インポートできない(Nothing import)
    - macでzip を解凍してみる →  .unitypackageを解凍した フォルダになってしまう
- VContainer.unitypackage があるフォルダを upload する → zip がアップロードされる
    - mac でzip を解凍してみる →  .unitypackageを解凍した フォルダになってしまう

という現象が起きていて、upload-artifact を経由すると 正しい unitypackageファイルを手に入れることができません。

--

```
Hmm.. 
I extracted the unitypackage and the contents are probably fine.

This problem is probably caused by upload-artifact.

My latest build has following step.

```yaml
    - uses: actions/upload-artifact@v2
      with:
        name: unitypackage
        path: VContainer.unitypackage
```

As a result, upload-artifact is a `VContainer.unitypackage.zip`, not `Vcontainer.unitypakcage`. 
This zip is not what Unity is expecting.

Similarly, there were problems with here:

```yaml
    - uses: actions/upload-artifact@v2
      with:
        name: unitypackage
        path: tmp/
```

When you unzip unitypackage.zip, it's a folder. I have been able to upload the VContainer.unitypackage It is not.
```

**Comment by hadashiA** [comment]
VContainer とは別問題になってきたので、一旦ここはCloseさせて下さい。
後々、 対応したいと思てます。

**Comment by hadashiA** [comment]
download-artifact で ダウンロードしたものを リリースに添付すると何も問題はありませんでした。
お騒がせしました! 🙏
