### ISSUE TITLE
Cannot register System.Type in IContainerBuilder

### ISSUE THREAD

**Issue by Razenpok** [hadashiA/VContainer#107]
I want to register all the types I need that derive from a certain interface, and there's no way to do this:

```csharp
var baseType = typeof(IUseCase);
var assembly = baseType.Assembly;
var useCaseTypes = assembly.GetTypes()
    .Where(t => baseType.IsAssignableFrom(t));
foreach (var useCaseType in useCaseTypes)
{
    builder.Register(useCaseType, Lifetime.Transient);
}
```

**Comment by hadashiA** [comment]
Agree. This is useful.
I will expose `Register(Type type, ...)`.
Thanks for the feedback.

**Comment by hadashiA** [comment]
Releaed in [v1.5.1](https://github.com/hadashiA/VContainer/releases/tag/1.5.1)
