### ISSUE TITLE
Cannot create custom RegistrationBuilder

### ISSUE THREAD

**Issue by Razenpok** [hadashiA/VContainer#108]
`IContainerBuilder` provides `public Register(RegistrationBuilder)` method which is completely useless given that all the constructors of `RegistrationBuilder` are `internal`. Taking this into account, there are two options:

1. Change it to ` internal IContainerBuilder.Register(RegistrationBuilder)`
2. Make `RegistrationBuilder` more open for extension

IMO (2) is a better option since I've already got into a situation where a custom `RegistrationBuilder` would be useful.

**Comment by hadashiA** [comment]
I got it. I would like to adopt your suggestion (2). That extensibility looks good.
I think suggestion (1) is also possible, but it is a bit complicated because it requires splitting the current interface members to make them internal.

**Comment by hadashiA** [comment]
@Razenpok
I am working on such a fix. #110 
Changed the constructor of RegistrationBuilder to public.

- Registration is still internal. However, the members of Registration can be controlled from the Builder.
- IRegistration is public

Does this fit for your use case?

**Comment by Razenpok** [comment]
Yeah, this fix should be enough for any case of extensibility I need. Thanks!

**Comment by hadashiA** [comment]
Releaed in [v1.5.1](https://github.com/hadashiA/VContainer/releases/tag/1.5.1)
