### ISSUE TITLE
support for dynamic objects / factories and generic unconstructed types

### ISSUE THREAD

**Issue by slimshader** [hadashiA/VContainer#11]
Hey, VContainer looks great but looking at the docs it seems it doesn’t currently support spawning of objects at runtime via Factories, is that the case? Same question for unconstructed generic types: for example is there a way to bind all types that implement interface IEventHandler<T> from specified Assembly?

**Comment by hadashiA** [comment]
@slimshader 

> it seems it doesn’t currently support spawning of objects at runtime via Factories, is that the case?

Hmm, I know many libraries support this. It deserves consideration.

But currently not supported.

I think it is not very important thing to inject to dynamic spawned object at runtime.

There are two reasons:
- Perhaps the objects created by the Factory are not of service class or any domain functionality, they're more granular. Therefore, I think a bit out of scope from a pure DI pattern.
- It may be possible to implement manually.

```csharp
class FooFactory
{
    readonly Settings settings;

    [Inject]
    public FooFactory(Settings settings)
    {
        this.settings = settings;
    }
 
    public Foo Create()
    {
        var foo = // ...
        foo.Configure(settings);
        return foo;
    }
}
```

Well, this is a bit redundant.
I might implement in the future if I come up with good API.

> is there a way to bind all types that implement interface IEventHandler from specified Assembly?

It also does not supported.
Is the function you are referring to something like the following ?

```        
    foreach (Type type in AllTypesInAssembly) 
    { 
        if (type.GetGenericTypeDefinition() == typeof(IEventHandler))
        {
            builder.Register(type)......
         }
    }
```

This is easy to implement, but performance seems bad.
Let me think about whether to implement it.

If you can tell me your use case, I may raise the priority.

**Comment by slimshader** [comment]
> @slimshader
> 
> > it seems it doesn’t currently support spawning of objects at runtime via Factories, is that the case?
> 
> Hmm, I know many libraries support this. It deserves consideration.
> 
> But currently not supported.
> 
> I think it is not very important thing to inject to dynamic spawned object at runtime.
> 
> There are two reasons:
> 
> * Perhaps the objects created by the Factory are not of service class or any domain functionality, they're more granular. Therefore, I think a bit out of scope from a pure DI pattern.
> * It may be possible to implement manually.
> 
> ```cs
> class FooFactory
> {
>     readonly Settings settings;
> 
>     [Inject]
>     public FooFactory(Settings settings)
>     {
>         this.settings = settings;
>     }
>  
>     public Foo Create()
>     {
>         var foo = // ...
>         foo.Configure(settings);
>         return foo;
>     }
> }
> ```
> 
> Well, this is a bit redundant.
> I might implement in the future if I come up with good API.

Best API I saw so far is from SimpleInjector (from the author of DI book): 

https://simpleinjector.readthedocs.io/en/latest/howto.html#register-factory-delegates

Clients simply inject Func<T> and the use it to instantiate dynamic objects;


> 
> > is there a way to bind all types that implement interface IEventHandler from specified Assembly?
> 
> It also does not supported.
> Is the function you are referring to something like the following ?
> 
> ```cs
>     foreach (Type type in AllTypesInAssembly) 
>     { 
>         if (type.GetGenericTypeDefinition() == typeof(IEventHandler))
>         {
>             builder.Register(type)......
>          }
>     }
> ```
> 

Yeah it is about generic unreconstructed types so typeof(IEventHandler<>). The case would be to be able to configure MediatR, example confghtations for various DI containers here:

https://github.com/jbogard/MediatR/wiki

**Comment by hadashiA** [comment]
- Lambda Factory is supported now
- ﻿Generic support is in a separate issue and draft. #301
