### ISSUE TITLE
Compatibility with DOTS/ECS?

### ISSUE THREAD

**Issue by MostHated** [hadashiA/VContainer#12]
Hey there, 
    I was thinking of trying this out and as I was reading the instructions I saw it had playerloop integration, which made me think it would be a good idea to ask if you happen to know if this is compatible with DOTS/ECS?

Thanks,
-MH

**Comment by hadashiA** [comment]
@MostHated 
Interesting question, but I think DOTS/ECS is a different paradigm from regular C# and OOP.

( In the Data Oriented design that Unity thinks of, data is a value type and heap allocation is strictly managed. So I think this is a completely different world from DI. )

But I'm not an ECS expert. If you have any ideas for a good way to work with ECS, please tell me specifically.  :)

**Comment by MostHated** [comment]
I can understand what you are saying in regards to paradigm, which is true for some aspects, but there are still plenty of places in which I think some form of DI could fit during the construction/setup of the ECS world. I may have to familiarize myself a bit more with the system first before I could say for sure. Though, I was more wondering if you happen to know if it was technologically compatible with ECS. 

I only ask because I saw in the forum posts that people using ECS ended up having issues when they attempted to use a 3rd party asset/package in which modifications were introduced into the playerloop. This very well could have been simply a matter of configuration and not some sort of technical limitation/incompatibility, though.

**Comment by hadashiA** [comment]
I decided to plan ECS integration.
I will try to support ComponentSystem Injection first.

**Comment by MostHated** [comment]
Good deal. I look forward to checking that out once it is implemented. 👍

**Comment by hadashiA** [comment]
OK. Today I understand the problem with ECS and third party PlayerLoop and I would like to report it.
( I was using GetCurrentPlayerLoop in Unity 2019.3, so I didn't notice it so far.

As API to register ECS `World` in PlayerLoop, `ScriptBehaviourUpdateOrder.UpdatePlayerLoop(world)` Is provided.

If we call it without a second argument, it will default to PlayerLoop with the first argument World added to it.
At this time, the difference between current and default is discarded, even if a third party modified current before that.

For Unity 2019.3 or later, we can avoid this problem by using PlayerLoop.GetCurrentPlayerLoop())

- Use `ScriptBehaviourUpdateOrder.UpdatePlayerLoop(world, PlayerLoop.GetCurrentPlayerLoop())`
  - ※The ECS default World uses the default PlayerLoop internally, so I think a third party should do it later.
- Use `PlayerLoop.GetCurrentPlayerLoop()` even when a third party rewrites PlayerLoop. (Like this repo)

However, in versions below 2019.3, I don't have `GetCurrentPlayerLoop`, so I think there will be a conflict in rewriting PlayerLoop...

**Comment by hadashiA** [comment]
I implemented the first feature about ECS. #18

After merging this, we should not have the PlayerLoop conflict issue in Unity 2019.3+ environments.

Any feedback is wellcome! :0

**Comment by MostHated** [comment]
This is great news. I will try and have a go at it when I get a chance. 👍
