### ISSUE TITLE
Missing `import` of `ComponentSystemBase`

### ISSUE THREAD

**Issue by quabug** [hadashiA/VContainer#131]
version 1.5.6
![image](https://user-images.githubusercontent.com/683655/108026458-58462f80-7063-11eb-8834-9ca84a41c92b.png)

**Comment by hadashiA** [comment]
Thanks for the report, it looks like the build with ECS is broken.

I've fixed it in #132.
I'm going to set up a CI to detect this though.

**Comment by hadashiA** [comment]
Released in [v1.5.7](https://github.com/hadashiA/VContainer/releases/tag/1.5.7)
