### ISSUE TITLE
Use specific named assembly to enable ability to access `ILPostProcessor`

### ISSUE THREAD

**Issue by quabug** [hadashiA/VContainer#138]
Assembly start with "Unity" and end with "CodeGen", for example "Unity.VContainer.CodeGen", is able to access unity's own `ILPostProcessor`, so vcontainer could rid of redistribution of "Unity.CompilationPipeline.Common.dll".

https://forum.unity.com/threads/how-does-unity-do-codegen-and-why-cant-i-do-it-myself.853867/#post-5646937

**Comment by hadashiA** [comment]
I have adopted your suggestion (#139).  Thank you.
