### ISSUE TITLE
CodeGen is not working on Unity 2020.2 or later.

### ISSUE THREAD

**Issue by hadashiA** [hadashiA/VContainer#141]
In 2020.2 and later, the behavior of ILPostProcessor seems to have changed.

- Unity's API seems to be unavailable.
    - UnityEngine.Debug.Log throws `MissingMethodException`
    - AssetDataBase / PlayerSettings also throws.
- Instance from ILPostProcessor is now always null.

**Comment by quabug** [comment]
There's a standalone .net core program to process `ILPostProcessor` rather than Unity now.
`Console.Write` seems work for a simple debug log, but it output into `Editor.log` file instead of `Console` window.

**Comment by hadashiA** [comment]
I am planning a change to deprecate the CodeGen setting in ScriptableObject (since it is not accessible from ILPostProcessor) and determine the target asmdef.

I've never heard of ILPostProcessorRunner before. I'll check it out. Thanks.
