### ISSUE TITLE
UnityEditorでの実行後にReflectionTypeLoadExceptionが発生する

### ISSUE THREAD

**Issue by hrs-o** [hadashiA/VContainer#164]
Windows 10
Unity 2020.3
VContainer.1.6.0 
MagicOnion.Client.Unity v4.1.2

起動時に放置していても問題ないのですが、UnityEditor上で一度Sceneを実行したあとに停止し、そのまま放置しておくと一定間隔ごとに例外が発生し続けています。

`ParentReferencePropertyDrawer#GetAllTypeNames`の`assembly.GetTypes`で例外が発生してしまいます。https://github.com/hadashiA/VContainer/blob/54a22b539f33466c89e8ca8bac60e3750879f803/VContainer/Assets/VContainer/Editor/ParentReferencePropertyDrawer.cs#L10-L25

例外が発生するとLifetimeScopeを貼っ付けてるオブジェクトのインスペクタが正しく表示されないようです。

- 例外発生前
![image](https://user-images.githubusercontent.com/7277266/112126653-04051100-8c08-11eb-81d2-fbcea8912f84.png)
- 例外発生後
![image](https://user-images.githubusercontent.com/7277266/112126652-02d3e400-8c08-11eb-95b8-58dec60e5109.png)

また、[MagicOnion](https://github.com/Cysharp/MagicOnion)とも関係しているようなのですが、VContainer側の処理の対応になるのかMagicOnion側か、もしくは私がなにかトチってるかが判別出来なかったため、こちらに記載させていただきました。

- 例外発生直前にassembly.CodeBaseで取得した値
  - `file:///D:/PATH/TO/Unity/Library/ScriptAssemblies/MagicOnion.Client.dll`
- 例外発生直前にassembly.FullNameで取得した値
  - `MagicOnion.Client, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null`
- スタックトレース
```
ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
System.Reflection.Assembly.GetTypes () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
VContainer.Editor.ParentReferencePropertyDrawer.GetAllTypeNames () (at Library/PackageCache/jp.hadashikick.vcontainer@e17b3fb9e9/Editor/ParentReferencePropertyDrawer.cs:18)
VContainer.Editor.ParentReferencePropertyDrawer.OnGUI (UnityEngine.Rect rect, UnityEditor.SerializedProperty prop, UnityEngine.GUIContent label) (at Library/PackageCache/jp.hadashikick.vcontainer@e17b3fb9e9/Editor/ParentReferencePropertyDrawer.cs:38)
UnityEditor.PropertyDrawer.OnGUISafe (UnityEngine.Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label) (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.PropertyHandler.OnGUI (UnityEngine.Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, System.Boolean includeChildren, UnityEngine.Rect visibleArea) (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.GenericInspector.OnOptimizedInspectorGUI (UnityEngine.Rect contentRect) (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass59_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <1d96ce257f0e45ff836d157d33fd933d>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
```

試したこと
- Menu->Assets->Reimport All
- Libraryディレクトリの削除

**Comment by hadashiA** [comment]
@hrs-o 詳細な報告 ありがとうございます。

MagicOnion.Client がなぜ型情報を取得できないか詳細は調べていないのですが、
ssembly.GetTypes では 型情報を取得できない場合があるみたいですね。
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.gettypes?view=net-5.0#exceptions

#165 で、 リフレクションで収集できない型情報を無視するように修正しました。

**Comment by hrs-o** [comment]
@hadashiA 対応ありがとうございます！
masterを参照するようにしたところ継続的に例外が出力される件は解決しました。
別件でもう一点確認したいことがあるので後ほどIssues作成させていただきます。
