### ISSUE TITLE
IStartableを実装しているとMagicOnionがクラッシュする

### ISSUE THREAD

**Issue by hrs-o** [hadashiA/VContainer#166]
- Windows 10
- Unity 2020.3
- VContainer.1.6.0
  - gitからmaster取得してます
  - d1fecbdd9341f6d49837dd0aebf8e4dd72e5f68a 時点
- MagicOnion.Client.Unity v4.1.2

下記の手順で[MagicOnion](https://github.com/Cysharp/MagicOnion)がクラッシュします。
LifetimeScopeがSceneにない状態でMagicOnionの実行が出来る、複数回の起動でクラッシュしていないことは確認済みです。
（今回のサンプルだと実行は確認出来ません）

## 手順

1. シーンにLifetimeScopeをつけたオブジェクトを置く
1. UnityEditor上でSceneを実行し、停止
1. 再度Sceneを実行

- 今回は検証のためほぼ空のSceneで実行したのでVContainerによるものかなと
![image](https://user-images.githubusercontent.com/7277266/112258278-93aecc00-8ca9-11eb-86f0-32549870cb8d.png)

## 読み込まれていると思われるスクリプト

- GameLifetimeScope.cs
```GameLifetimeScope.cs
using VContainer;
using VContainer.Unity;

public class GameLifetimeScope : LifetimeScope
{
    protected override void Configure(IContainerBuilder builder)
    {
        builder.Register<HelloWorldService>(Lifetime.Singleton);
        builder.RegisterEntryPoint<GamePresenter>(Lifetime.Singleton);
    }
}
```
- HelloWorldService.cs
```HelloWorldService.cs
public class HelloWorldService
{
  // 読み込ませるだけなので処理なし
}
```
- GamePresenter.cs
```GamePresenter.cs
using VContainer.Unity;

public class GamePresenter : IStartable
{
    private readonly HelloWorldService _helloWorldService;

    public GamePresenter(HelloWorldService helloWorldService)
    {
        _helloWorldService = helloWorldService;
    }
    void IStartable.Start()
    {
        // 特に何もしない
    }
}
```

### 備考

GamePresenter.csからIStartableの実装を抜いた状態にするとクラッシュしなくなりました。
ただし、一度クラッシュするようになっているとUnity再起動するまで関係なくクラッシュし続けるようです。

```diff
- public class GamePresenter : IStartable
+ public class GamePresenter
{
    private readonly HelloWorldService _helloWorldService;

    public GamePresenter(HelloWorldService helloWorldService)
    {
        _helloWorldService = helloWorldService;
    }
-    void IStartable.Start()
-    {
-        // 特に何もしない
-    }
}
```

## Unity Consoleに出力されたエラー

```
Error: Could not load signature of MagicOnion.ChannelExtensions:RegisterStreamingSubscription due to: Could not load file or assembly 'Grpc.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad' or one of its dependencies. assembly:Grpc.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad type:<unknown type> member:(null) signature:<none>

```

```
Error: Could not load signature of MagicOnion.MetadataExtensions:Get due to: Could not load file or assembly 'Grpc.Core.Api, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad' or one of its dependencies. assembly:Grpc.Core.Api, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad type:<unknown type> member:(null) signature:<none>
```

```
Unloading broken assembly Library/ScriptAssemblies/MagicOnion.Unity.dll, this assembly can cause crashes in the runtime
```

```
Unloading broken assembly Library/ScriptAssemblies/MagicOnion.Client.dll, this assembly can cause crashes in the runtime
```

**Comment by hadashiA** [comment]
@hrs-o  とりあえず MagicOnion をインストールしただけの状態では再現しませんでした。
以下のいずれか もらえると助かります…、

- 問題が再現する(最小)プロジェクト
- もしくは、スクラッチの状態から 再現する MagicOnion 他の設定なども含めた手順

**Comment by hrs-o** [comment]
@hadashiA

確認いただきありがとうございます。
自分の環境だと下記リポジトリをcloneしたプロジェクトで再現するのですがいかがでしょうか？

https://github.com/hrs-o/VCMO-Test

![gif](https://user-images.githubusercontent.com/7277266/112611276-f5fdfd00-8e60-11eb-8f42-f5e65a768949.gif)


## gRPCプラグインについて

gRPCプラグインが100MB超えており、リポジトリに含んでおりませんのでお手数ですが別途DLとインポートが必要です。

### DL

- 下記URLの`grpc_unity_package.2.37.0-dev202102141315.zip`をDL
  - https://packages.grpc.io/archive/2021/02/6102f67adeccb95afb32c2cef4198e50a5d77ee0-e2604501-c4b3-453d-bd11-fb9374a2fed8/index.xml
![image](https://user-images.githubusercontent.com/7277266/112607934-188e1700-8e5d-11eb-9dcd-5636bddc28f0.png)


### インポート

- 解凍したzipの「Grpc.Core、「Grpc.Core.Api」を`Assets/Plugins`配下にコピー
![image](https://user-images.githubusercontent.com/7277266/112608229-6dca2880-8e5d-11eb-955d-5610b4a26f36.png)

## 自前で書いたscript

- `Assets/Scripts/MyApp`配下

## 対象Scene

- Assets/Scenesの`SampleScene`

**Comment by hadashiA** [comment]
@hrs-o 再現プロジェクトをありがとうございます。

確認したところ、VContainer が Assembly-CSharp のILを書き換えようとしてしまうことで発生するエラーのようでした。
- 上記プロジェクトの場合、 gRPC や System.Memory 等のポリフィルが Assembly-CSharp に含まれています。
- また、症状としては、IStartable の有無は関係がなく、プロジェクトを開いた後の コードの編集後のコンパイルが走ると起こる、という状況だと思います。

#167 で修正されたバージョンのVContainerを使うと エラーが出なくなることが確認できました。
ご確認いただければと思います。

**Comment by hrs-o** [comment]
@hadashiA 1.6.1で問題が再現しなくなったのを確認しました、ありがとうございます！
