### ISSUE TITLE
RegisterInstanceで登録したインスタンスの生存期間を設定したい

### ISSUE THREAD

**Issue by sakano** [hadashiA/VContainer#169]
ver1.6.0現在、RegsiterInstanceで登録したインスタンスは全てLifetime.Scopedで管理されているようです。
それによってIDisposableを実装したインスタンスがLifetimeScopeごとにDisposeされてしまっています。

LifetimeScopeに親子関係を持たせる場合、子のLifetimeScopeが破棄されると親のLifetimeScopeでも登録したインスタンスがDisposeされた状態になるので困ってしまいます。

RegisterInstanceのタイミングでLifetimeも指定できるAPIがあると嬉しいです。

**Comment by hadashiA** [comment]
> LifetimeScopeに親子関係を持たせる場合、子のLifetimeScopeが破棄されると親のLifetimeScopeでも登録したインスタンスがDisposeされた状態になる

お。どちらかというと この挙動が おかしいですね。。
子のDisposeが親のインスタンスに影響しないように修正されれば問題ないでしょうか ?

> RegisterInstanceのタイミングでLifetimeも指定できるAPI

個人的には、生成済みのインスタンスが使用される場合は、生成タイミングと寿命を変更のしようがないので、ライフタイムの指定はナンセンスかなと思っています。

**Comment by sakano** [comment]
外で作ったインスタンスをLifetimeScopeに管理してほしくないのでLifetime.TransientにしてDisposeされないようにしたい、などと考えていました。
そもそもIDisposableでない形で渡せば回避できるのでLifetime.Singleton固定でも大丈夫です。

**Comment by sakano** [comment]
Lifetime.Singleton固定でも大丈夫、と書きましたがもう少し考えてみました。

#171 のプルリクだとResolveされた場合にのみDisposeされることになりそうです。
RegisterInstanceした段階ではDisposeが呼ばれるか不定なのでかなり使いづらいことになります。

登録されたインスタンスをDIコンテナが破棄すべきかはAutofacでも議論になっていました。
https://github.com/autofac/Autofac/issues/780
結論としてはデフォルトで破棄して、破棄させたくない場合は明示的にExternallyOwned()を付けるようです。

Resolveされるかに関わらず必ず破棄されるように直すのは面倒な気もするので、VContainerでは破棄しないとするのもいいのではいでしょうか。
autofacの議論でも破棄しない方がよさそう、と言いながら現状の形になったのは互換性のためではないかと思います。はっきり書かれていないので推測になりますが。
私としても破棄する責任を持つのはインスタンスを生成した側、とするのが自然だと感じます。

**Comment by hadashiA** [comment]
>  RegisterInstanceした段階ではDisposeが呼ばれるか不定なのでかなり使いづらいことになります。

これはたしかにそうですね。
Resolveの有無に関わらず同じ挙動をしないとわかりずらいですね。

僕としては、どこからも Resolve されないのに RegisterInstance されている状態がそもそもあまり望ましくないと思っていたりしますが、とはいえ 挙動は統一されて良いとは思います。

>  結論としてはデフォルトで破棄して、破棄させたくない場合は明示的にExternallyOwned()を付けるようです。

自分は どちらかというとこの挙動(デフォルトでコンテナが破棄)のほうがしっくりきていたりします。

RegisterInstance したものをコンテナに破棄してほしいかどうかは、場合によるのではないでしょうか。
- 自力で どこかでDispose を呼ぶ必要がある場合には、コンテナに管理を委譲できるほうが自然な気がしてます
- コンテナ経由 で 使用できるインスタンスが、外でDisposeされているかもしれない (コンテナより寿命が短いかもしれない)というのは微妙に予想外な気がします

ただ 、どちらをデフォルトにするかはともかく、双方の機能を選択できるのがよさそうです。
autofac の issueも参考になります。ありがとうございます

**Comment by hadashiA** [comment]
`RegisterInstance` の挙動を検討しましたが、少し考えが変わりました。やはり提案してもらった案を採用しようと思います。


変更:
- `RegisterInstance` で登録したインスタンスはコンテナで管理しない
  - 自動的なDispose は実行されない
  - また、メソッドインジェクションも実行されない


理由:
- autofac の `.ExternallyOwned()` によるコントロールは少し煩雑で 初見で少し意味がわかりずらい
- `Microsoft.Extensions.DependencyInjection` は上記の挙動になっている
  - https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#service-registration-methods
- 生成済みインスタンスを管理させたい場合には既に他のオプションがある
  -  #206 で追加したラムダ式にキャプチャさせる ( e.g: `Register(_ => instance, ..)` 
  - RegisterComponent を使用する

**Comment by hadashiA** [comment]
Released in [v1.8.0](https://github.com/hadashiA/VContainer/releases/tag/1.8.0)

参考になりました。また何かあればお願いします。
