### ISSUE TITLE
LifetimeScope 派生クラスと Script Execution Order について

### ISSUE THREAD

**Issue by nayuta-cr** [hadashiA/VContainer#186]
LifetimeScope のインスペクターでは Auto Inject Game Objects を設定することができ、
実行時設定した GameObject 以下の MonoBehaviour (※) へ inject できるようになっています。

LifetimeScope 派生クラスでこの Auto Inject Game Objects 機能を使用してみたところ、実行時に※への injection が起こるタイミングでは既に※のAwake() や OnEnable() が実行済みであることがありました。Auto Inject Game Objects を利用した injection は、シーン中の他のコンポーネントの Awake() や OnEnable() が実行されるよりも前に起こると思い込んでいたのでこの結果は意外でした。

これは LifetimeScope 派生クラスと※の Script Execution Order が何れもデフォルト(=0)であり、どちらの Awake() が先に実行されるかが決まっていないためだと思われます。実際、LifetimeScope 派生クラスの Script Execution Order を -9999 に設定したところ、※のAwake()が実行される前に injection が起こり、意図通りの動作となりました。

- LifetimeScope 派生クラスが(Script Execution Order の意味で)なるべく素早く実行されるよう実装されているとありがたいです。
- あるいはそれが無理でも、ドキュメントに Script Execution Order に関する記述があるとありがたいです。

なお、Zenject では Zenject.SceneContext の Script Execution Order は -9999 に設定されており、injection はシーン中の他のコンポーネントの Awake() や OnEnable() が実行されるようにも前に起こりますが、このことが私の思い込みの原因であったと思います。

**Comment by nayuta-cr** [comment]
(本文など記述する前にうっかり投稿してしまいました。申し訳ありません)

**Comment by hadashiA** [comment]
なるほど。 指定したほうがよさそうです

( LifetimeScope の派生クラスに設定が反映される必要がありますが、 `[DefaultExecutionOrder]` attributeを使えば良いのかな (?) 検証してみます。

**Comment by hadashiA** [comment]
派生 クラスにも設定が反映されるようなので、 `DefaultExecutionOrder` を追加しようとおもいます。  #194

**Comment by hadashiA** [comment]
Released in [v1.7.2](https://github.com/hadashiA/VContainer/releases/tag/1.7.2) .

( もしまだ挙動に問題があれば教えて下さい

**Comment by nayuta-cr** [comment]
1.7.2 ですべてうまく動作しました。

LifetimeScope 派生クラスが他のコンポーネントよりも先に動作し、
injection が実行された後で他のコンポーネントのAwake()やOnEnable()が呼ばれることを確認いたしました。

ありがとうございました。
