### ISSUE TITLE
VContainer.EnableCodeGenを参照したアセンブリがあるとビルドが失敗する（Unity 2021以降のみ？）

### ISSUE THREAD

**Issue by c3-hoge-fuga-piyo** [hadashiA/VContainer#187]
お世話になっております。

Unity 2021.2.0a13 （Windows）にて、 `VContainer` 並びに `VContainer.EnableCodeGen` を `Assembly Definition References` に追加した `asmdef` があると次のエラーでビルドが失敗してしまうようになっておりました。

```
(0,0): error VContainer failed pre code gen for <Module> : Could not load file or assembly '該当のアセンブリ名, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. General Exception (0x80131500)
```

最小の手順としては次になります。

1. 適当なディレクトリに `asmdef` を作る
2. (1) の `Assembly Definition References` に `VContainer` と `VContainer.EnableCodeGen` を追加する（コード生成の対象にする）
3. (1) のディレクトリに適当なスクリプトを追加する
4. ビルド実行
5. 失敗する 

またこちらですが、手元では `2021.1.3f1` と `2021.2.0a10 ~ 13（10より前については確認していません……）` でも同様のエラーが発生しておりました（ `2020.3.4f1` 、`2019.4.23f1` では問題なくビルドが通ります）

原因の特定までに至らなかったのですが、今後のバージョンアップの参考になればと思い報告させていただきます :bow:

**Comment by hadashiA** [comment]
報告ありがとうございます!

手元でも再現したので 修正してみました #196 
また問題があれば教えていただければ-

**Comment by c3-hoge-fuga-piyo** [comment]
迅速な対応ありがとうございます！

**Comment by c3-hoge-fuga-piyo** [comment]
こちらでも発生しなくなったことを確認できたのでクローズさせていただきます :bow: :tada: 

ご対応ありがとうございました！

**Comment by JesseTG** [comment]
Unfortunately, I still have this issue. This occurs on Unity 2021.1.3f1 on Windows 10.

**Comment by WoLfulus** [comment]
> Unfortunately, I still have this issue. This occurs on Unity 2021.1.3f1 on Windows 10.
> 
> At least, I think I have this issue; I'm relying on Google Translate to interpret this ticket. A workaround is to remove all references to .`VContainer.EnableCodeGen`

Have you managed to get this working? I have the same problem but with `Unity.InputSystem`. 

```
(0,0): error VContainer failed pre code gen for Game.ActionDispatcher : System.IO.FileLoadException: Could not load file or assembly 'Unity.InputSystem, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null'. General Exception (0x80131500)
```

Unity 2021.3.5f1
