### ISSUE TITLE
guid is missing

### ISSUE THREAD

**Issue by fumobox** [hadashiA/VContainer#2]
VContainer/Assets/VContainer/Runtime/VContainer.asmdef.metaがignoreされているようなので、
VContainer/Assets/VContainer/Editor/VContainer.Editor.asmdefと
VContainer/Assets/VContainer/Tests/VContainer.Tests.asmdefに登録されているguidが参照できないようです。

**Comment by hadashiA** [comment]
Oh.. たしかに.metaがignoreされちゃってますね...
unitypackageは無事みたいですが、リポジトリのファイルをインポートすると壊れますね。 
#4 で修正しました ><

It's true that .meta hasn't been committed...
The unity package seems safe, but when I import the files from the repository it's broken.
