### ISSUE TITLE
ヒエラルキー上の複数のオブジェクトに対してRegisterComponentInHierarchy()が動かない

### ISSUE THREAD

**Issue by miyamonz** [hadashiA/VContainer#215]
このようなコンポーネントを作り、ICameraRigをinjectしています
```cs
// 実行時にparentを変更するだけのスクリプト
public class ParentToTrackingPoint : MonoBehaviour
{
    ICameraRig cameraRig;
    [Inject]
    public void Construct(ICameraRig cameraRig)
    {
        this.cameraRig = cameraRig;
        Debug.Log(cameraRig);
    }
    [SerializeField]
    private TrackingPoint trackingPoint;
    // Start is called before the first frame update
    void Start()
    {
        Debug.Log(cameraRig);
        var t = cameraRig.GetTransform(trackingPoint);
        transform.SetParent(t, false);
        
    }

}
```

configure
```cs
        builder.RegisterEntryPoint<OculusCameraRig>(Lifetime.Singleton); //ICameraRigの実装
        builder.RegisterComponentInHierarchy<ParentToTrackingPoint>();
```

このとき、ヒエラルキー上でこのコンポーネントを持つオブジェクトが複数ある場合、最初の一つのみにinjectされているようです。
ヒエラルキー上で２つのオブジェクトの順番を入れ替えると、最初の方のみが正しく動いています。

これはバグでしょうか？それとも私のDIに関する勘違いでしょうか？（当方Unityのプログラミングに慣れていないため勘違いであったら申し訳ないです）

**Comment by sakano** [comment]
DIに同じ型のオブジェクトを複数Registerするのはあまりいい使い方ではない気がします。
他のクラスからParentToTrackingPointを使おうとしたときに複数あるうちのどちらがinjectされるのかわかりづらくなるので。
(一応VContainerでは後にRegisterされたものが優先されるようです。[#189])

なのでRegisterComponentInHierarchyで最初の1つだけしか動かないのはバグではないように思います。

そんなRegisterComponentInHierarchyが動かないなら、ParentToTrackingPointは自分で見つけてきてRegisterComponentで登録してしまえば動きます。
```cs
// GetComponentsInChildrenで探して登録する
foreach (var trackingPoint in GetComponentsInChildren<ParentToTrackingPoint>())
{
    builder.RegisterComponent(trackingPoint);
}
```


もしRegisterする必要が無い(= ParentToTrackingPointが他でinjectされることがない)ならRegisterBuildCallbackでInjectを呼べば登録せずにParentToTrackingPointに対するinjectだけができます。
```cs
// GetComponentsInChildrenで探してInjectする
foreach (var trackingPoint in GetComponentsInChildren<TestMonoBehaviour>())
{
    builder.RegisterBuildCallback(resolver =>
    {
        resolver.Inject(trackingPoint);
    });
}
```

もしくはLifetimeScopeのAutoInjectGameObjectsにParentToTrackingPointがついたGameObjectを設定しても動くと思います。

**Comment by miyamonz** [comment]
ありがとうございます！自分が勘違いしているのがわかりました。
RegisterはInjectの注入内容と注入先の同時登録をしてるので、複数の同じコンポーネントを注入内容として登録するのはおかしいですね。
今回の例だとAutoInjectGameObjectsを使うのが良さそうです。意図通りにも動きました。

ヒエラルキーの中にinjectしたいなら書いてもらった方法を使えばよいので、RegisterComponentInHierarchyは、ヒエラルキー内に存在する何かを別のどこかに注入したいときに使うものと理解しました
