### ISSUE TITLE
Proposal: Add virtual LifetimeScope.OnAfterBuild(IObjectResolver)

### ISSUE THREAD

**Issue by sakano** [hadashiA/VContainer#224]
I would like to write the process after IContainerBuilder is built as follows.

```cs
public class CustomLifetimeScope : LifetimeScope
{
    protected override void Configure(IContainerBuilder builder)
    {
    }

    // I want this virtual method!!!
    protected override void OnAfterBuild(IObjectResolver resolver)
    {
        resolver.Inject(obj);
    }
}
```

I can do the same with `builder.RegisterBuildCallback`, but it is hard to understand at first glance.
I think it will be easier to understand if we can standardize how to write as shown above.

**Comment by hadashiA** [comment]
Hmm, it is probably easy to understand. But I have my doubts about its necessity.

- I think there is also a simplicity in being able to do everything with the `builder` API.
  - What's the difference with `builder.RegisterBuildCallback`? Users may be wondering.
- We may not want to actively increase the number of ways to directly access the IObjectResolver.

However, according to your suggestion, there may be a problem of insufficient documentation.

**Comment by hadashiA** [comment]
I have decided not to implement this feature for now.
If you have another opinion on the need or use case of LifetimeScope override, reopen is welcome.

**Comment by hadashiA** [comment]
Added the documentation on RegisterBuildCallback. Just a few things. #240
