### ISSUE TITLE
Semi-Transient lifetime of entry points

### ISSUE THREAD

**Issue by longbombus** [hadashiA/VContainer#238]
I faced a case where ITickable should be resolved in Transient way.
I have registration
```
builder.RegisterEntryPoint<ComboCounter>(Lifetime.Transient).AsSelf();
```
So each spawned ComboCounter is resolved but ticks are executed for other instances, which are created as ITickable for EntryPointDispatcher.
I admit the logic of this behavior. But ITickable and other entry points are treated as simple way to integrate player loop logic into C# class, however user fated to build their own player loop binding in that case.

Would it be a good decision to execute entry points only for instances that Transient resolved without entry point interfaces?

**Comment by hadashiA** [comment]
I agree that the behavior of EntryPoint in Transient is strange.

The API to specify Lifetime for EntryPoint was probably a mistake!.
Therefore, I made a fix to make the argument unnecessary by default.
https://github.com/hadashiA/VContainer/pull/248

> ITickable and other entry points are treated as simple way to integrate player loop logic into C# class, however user fated to build their own player loop binding in that case.

If you need a control to call `Tick()` from other object, it's not likely to be an "EntryPoint", so I'm thinking it's better to use a regular Inject.
