### ISSUE TITLE
Missing "None" option for Parent scope in 1.8.1

### ISSUE THREAD

**Issue by slimshader** [hadashiA/VContainer#242]
In the 1.8.1 version there is no "None" option to select in Parent section of a LifetimeScope. It is there in 1.8.0

**Comment by hadashiA** [comment]
Oops... Thanks for the report, Fixed in #243.

**Comment by hadashiA** [comment]
Released in [v1.8.2](https://github.com/hadashiA/VContainer/releases/tag/1.8.2)
