### ISSUE TITLE
Multiple LifetimeScopes in a single scene loaded additively

### ISSUE THREAD

**Issue by slimshader** [hadashiA/VContainer#245]
Hi,

I have a scene with 3 lifetime scopes:
Scope A, parent None
Scope B, parent A (configured in Inspector)
Scope C parent A (configured in Inspector)

I am adding this scene from another scope (Z) that I want as a parent for scope A:

using (LifetimeScope.EnqueueParent(Scope Z))
{
  await LoadSceneWithSetupAbove()
}

the problem is it seems that parent for B and C is also overridden and becomes Z so A, B and C all have parent Z but what I want to achieve is:

A parent Z (from EnqueueParent)
B parent A (as configured in inspector)
C parent A (as configured in inspector)

**Comment by hadashiA** [comment]
Admittedly, in this case it is not practical to be replaced by Z.

I would change it to just override the parent if it doesn't exist.
Probably because it has a minor impact.

--

On the other side.
I'm a little skeptical about the necessity of a fine grain LifetimeScope stored in a scene.
It seems complicated to set up strict relationships and visibility in advance.

**Comment by slimshader** [comment]
The need for such setup came when we tried to port one of our projects from Zenject to VContainer to see if it was practical / possible as our Zenject configuration is quite complex.

In the case of Zenject (and our original setup) Scope B and C were GameObjectContexts in Zenject nomenclature with Scope A being SceneContext (automatic parent for B and C).

**Comment by hadashiA** [comment]
Ok, I understand the use case.
I would like to support relationships on the same scene as much as possible.

#249 changed the priority of EnqueueParent. I hope you will try it.

**Comment by slimshader** [comment]
> Ok, I understand the use case.
> I would like to support relationships on the same scene as much as possible.
> 
> #249 changed the priority of EnqueueParent. I hope you will try it.

Great, will try for sure hopefully by the end of week

**Comment by hadashiA** [comment]
The fix is out, so if you have any problems, please reopen it!
