### ISSUE TITLE
Feature request: Ability to list all registrations (for debugging purposes)

### ISSUE THREAD

**Issue by JesseTG** [hadashiA/VContainer#270]
It would be useful to see information about all the registrations within an `IObjectResolver`; this way you could ensure that your registered dependencies have the types you expect them to have.

I haven't much thought about what the API for listing registrations would look like, but I think the following information from it would be useful:

- The properties of each `IRegistration` implementation, including `ImplementationType`, `InterfaceTypes`, and `Lifetime`
- The type of the `IRegistration` itself
- For instance registrations, the instance that was registered (including factories)
- For transient registrations, the number of times that the dependency was resolved (and therefore the number of instances that were created)
- For scoped registrations, the scope under which it was registered
- The status of each registration (i.e. has anything resolved it yet?)

A custom drawer as part of `LifetimeScope` would be ideal, but even just exposing an API would be enough for a debug command on a console plugin or something.

**Comment by hadashiA** [comment]
Maybe looks good.

It's not simple to think of an API only.
It would be nice to be able to release it with debugging features that are actually useful.

Let me know if you have plans for debugging features.

**Comment by JesseTG** [comment]
Ah, here's an idea; a way to list at runtime the order in which dependencies are resolved when the container is built. This would simplify debugging of implicit dependencies.

**Comment by hadashiA** [comment]
I would like to create a Debug Window in the Unity Editor.
For example, the following.

In the process of developing the GUI, I would like to consider adding necessary features to the IObjectResolver.

## ECS Entity Debugger

<img width="784" alt="Screenshot 2018-03-20 18 19 24" src="https://user-images.githubusercontent.com/727159/130719990-360fdee7-9fa1-4797-87e1-ed31f2918ce2.png">

## MessagePIpe Diagnostics Window

![116953319-e2e41580-acc7-11eb-88c9-a4704bf3e3c9](https://user-images.githubusercontent.com/727159/130720073-e697f6f1-b249-4482-b806-848e2e1643a1.png)
