### ISSUE TITLE
Is there already a way to configure RegisterEntryPoint registration?

### ISSUE THREAD

**Issue by NeistH2o** [hadashiA/VContainer#282]
Hello there!

### The problem
I've got 2 scenes `Client` and `Server` both loaded in the hierarchy, each have a gameobject with the component `ClientLifetimeScope : LifetimeScope` and `ServerLifetimeScope : LifetimeScope` respectively.

So two scopes in 2 different scenes.

Both of those scopes need to register the same `DebugMonitorService` class, ideally with entry points.

So I tried registering this class in both scopes like this but it fails:

![registering-dependency](https://user-images.githubusercontent.com/25915415/125334458-b0037100-e34b-11eb-8e53-5edf9d5201cb.PNG)
![register-entry-point-works-in-client-scene](https://user-images.githubusercontent.com/25915415/125333493-99a8e580-e34a-11eb-9160-63f187dbf929.PNG)

I'm probably doing something wrong here but so far I didn't figure out what.

Then, with the prefab being only used by that class I thought it wasn't necessary to register it, but instead simply pass it with a custom configuration like this:

![works-as-well-but-cannot-register-this-way-with-register-entry-point](https://user-images.githubusercontent.com/25915415/125334691-f2c54900-e34b-11eb-8b44-40712ff281e1.PNG)

Which works as expected, except that `RegisterEntryPoint` doesn't seem to have an overload available to specify the configuration like `Register` does.

### The question(s)
- Am I doing something really wrong with the first `RegisterEntryPoint` registration?
- Is there already a way to configure `RegisterEntryPoint` registration?
- Is it possible to implement an overload similar to `Register` for `RegisterEntryPoint`?

---
### Interesting side note

Both `DebugMonitorService` created when using `Register` happen to create a gameobject using `new Gameobject(...)` when injected, and I noticed that both gameobjects end up in the `Client` scene, while I kinda expected each to be created in the same scene as their respective scope.

![the-gameobject-created-by-the-server-scope-gets-created-inside-client-scene](https://user-images.githubusercontent.com/25915415/125335950-6ddb2f00-e34d-11eb-9687-d1985ebf31f2.PNG)

It's not a problem for me and maybe it's totally irrelevant, but I thought it might be interesting to point it out.

Thank you much in advance :)

**Comment by hadashiA** [comment]
@NeistH2o Sorry for late response.

> So I tried registering this class in both scopes like this but it fails:

The above code seems to work, but what is actually happening with "fails"?

Problems I can think of:

- In case of VContainerExcpetion (Cannot resolve a prefab):
    - As<>()` or `.AsImplementedInterfaces()` is needed if `DebugMonitorService` requires abstract types like interfaces.
- NullReferenceException:
    - If you are referring to an instance on another scene, you need to share the files in Assets/.


But both may be missing the point.

If you show me the implementation code of the class, I might be able to figure it out a little better.

**Comment by NeistH2o** [comment]
I'm closing this because I don't remember exactly how my scenes were setup but I m almost certain I was doing something wrong with the scopes in different scenes. If I get back to this I will create a new issue with proper logs attached to it :)
