### ISSUE TITLE
EntryPoint not working on LifetimeScope with specified parent

### ISSUE THREAD

**Issue by artahc** [hadashiA/VContainer#284]
I have 2 lifetime scope, which is `GlobalLifetimeScope` and `SomeSceneLifetimeScope` . I make `GlobalLifetimeScope` as root lifetime scope on `VContainer Settings`. 
In the hierarchy, i set the parent of `SomeSceneLifetimeScope` to `GlobalLifetimeScope` (in the inspector). And then in the `SomeSceneLifetimeScope` i register an entryPoint, but it's not working. 

What i was trying to achieve is: the entry point that is registered in `SomeSceneLifetimeScope` needed some singleton dependency that i registered in `GlobalLifetimeScope`, and i dont want to register a same class in both scope. 

I'm very new to DI, so my thinking is probably wrong...

**Comment by hadashiA** [comment]
@artahc  Are the `GlobalLifetimeScope` and `SomeSceneLifetimeScope` `Awake`s running?

Note:
If the GlobalLIfetimeScope is prefab, it probably won't start processing.

Try this if you want to specify prefab as the parent.
https://vcontainer.hadashikick.jp/scoping/project-root-lifetimescope

**Comment by artahc** [comment]
> If the GlobalLIfetimeScope is prefab, it probably won't start processing.
I see, yes it's a prefab that i registered as root lifetime scope in vcontainer settings. So i guess this is expected behaviour?

**Comment by hadashiA** [comment]
Oh, ok. It should work. There might be a bug.

One of the issues I'm aware of is that if Unity's Domain Reloading is disabled, VContainer Settings may not work in the editor unless you run the compile once.
https://docs.unity3d.com/Manual/DomainReloading.html

But this could be another cause. I would like some more information.
If you have a reproducing project/code, I'd appreciate it if you'd let me know.

**Comment by hadashiA** [comment]
@artahc  I found a bug in RootLifetimeScope and EntryPoint. I have fixed it in #289, please check it.
