### ISSUE TITLE
No Mono.Cecil in package

### ISSUE THREAD

**Issue by miv** [hadashiA/VContainer#29]
Mono.Cecil is missing from unity package. Nuget version https://www.nuget.org/packages/Mono.Cecil/ works fine.

**Comment by hadashiA** [comment]
As you say, there seems to be a problem with the installation from unitypackage...

However, I do not want to include a huge library, so I recommend installing from the Unity Package Manager for the time being.

Add the following to `Packages/manifest.json` of your project.

```json
    "nuget.mono-cecil": "0.1.6-preview"
```

**Comment by miv** [comment]
Great solution. Thank you.
