### ISSUE TITLE
How to resolve dependencies in non-registered class

### ISSUE THREAD

**Issue by miv** [hadashiA/VContainer#30]
Hello! I've been playing with VContainer, and i can't find our how to make one thing. 

I have some MonoBehaviours "presenters" that inserted into prefab and they need their model dependency. What is the proper way to do that? It there a way to inject dependencies into current class? 

EDIT: I should add that in this is basically to support some legacy code. Currently i think best way it to save main LifetimeScope to some global variable and resolve using Lazy<T>.

**Comment by hadashiA** [comment]
Hello.

How about considering 2 plans?

## 1. Create child scope

The name "presenters" suggests that there are a number of dependencies that involve the generation of related components.
I think that context will be created each time presenters are generated, so why not dynamically create a child LifetimeScope from the prefab?

e.g.:

```csharp
class ChildLifetimeScope : LifetimeScope
{
    [SerializeField]
    FooPresenter presenterPrefab;

    protected override void Configure(IContainerBuilder builder)
    {
        builder.RegisterComponentInNewPrefab(presenterPrefab, Lifetime.Scoped);
        // ... And some registration for dependencies
    }
}
```

And in a place that manages your scope and loading, do the following.

```csharp
// Create child. Presenter is also created here.
var child = parentLifetimeScope.CreateChildFromPrefab(childLifetimeScopePrefab);
```

## 2. Implement Factory manually

Inject from DI to Factory,
And let the Factory be responsible for initializing the dynamically created instance.

```csharp
class PresenterFactory
{
    readonly FooPresenter presenterPrefab;
    readonly SomeDependency dependency;

    public PresenterFactory(FooPresenter presenterPrefab, SomeDependency dependency)
    {
        this.presenterPrefab = presenterPrefab;
        this.dependency = dependency;
    }

    public FooPresenter Create()
    {
        var instance = Object.Instanciate(presenterPrefab);
        instance.Construct(dependency);
        return instance;
    }
}
```

**Comment by miv** [comment]
Thank you for through response.

But what if presenter is part of hierarchy? 

Basically, in Zenject terms, what i was looking for is `DiContainer.InjectGameObject` (or even `ZenAutoInjecter`) and `DiContainer.Inject`. I'll probably hack one in, but it would be great to have it as an official part of the library.

**Comment by hadashiA** [comment]
> But what if presenter is part of hierarchy?

Maybe for now, there is also a way to call `GetComponent` manually.

```csharp
protected override void Configure(IContainerBuilder builder)
{
    var instance = Instantiate(prefab);
    foreach (var x in  instance.GetComponents<MonoBehaviour>();)
    {
        builder.RegisterComponent(x).As(x.GetType());
    }
}
```

> but it would be great to have it as an official part of the library.

I see, I don't currently support the feature you say.

Hmm , I will consider support for this.

**Comment by hadashiA** [comment]
@miv Sorry for the late response.

I don't know if it's similar to your request,
From 1.3.0, I have added the function to set Container.Inject and GameObject that executes only Inject. (This is in the Lifetime Scope Inspector) Please check.
