### ISSUE TITLE
 Support dynamic registration from open generic type

### ISSUE THREAD

**Issue by hadashiA** [hadashiA/VContainer#301]
For example, I would like to be able to quickly register a generic like this.
https://github.com/Cysharp/MessagePipe/blob/master/src/MessagePipe/ServiceCollectionExtensions.cs#L43-L102

**Comment by slimshader** [comment]
Hi, what is the status of this one?

**Comment by voreshmag** [comment]
Hi, I am also interested in this feature

**Comment by slimshader** [comment]
Bump

**Comment by hadashiA** [comment]
#367 merged.
