### ISSUE TITLE
Move assignability check from building to resolution.

### ISSUE THREAD

**Issue by longbombus** [hadashiA/VContainer#308]
I would reach a easy way to register auto creatable prefabs.
So scope have such implementation:
```C#
[SerializeField] private Component[] prefabs;

protected override void Configure(IContainerBuilder builder)
{
	foreach (var prefab in prefabs)
	{
		var prefabType = prefab.GetType();
		builder
		.Register(c => c.Instantiate(prefab.gameObject).GetComponent(prefabType), Lifetime.Transient)
		.As(prefabType);
	}
}
```
It registers all `Component`-prefabs as its real type. But builder forbids it at `RegistrationBuilder.AddInterfaceType` when
```C#
if (!interfaceType.IsAssignableFrom(ImplementationType))
{
    throw new VContainerException(interfaceType, $"{ImplementationType} is not assignable from {interfaceType}");
}
```
It can be checked at runtime while resolving, because real object type can be assignable which is not checkable while registration.

**Comment by hadashiA** [comment]
Hmm, I want to be that all validation invoked at container build phase completly. And, container instance is as guaranteed as possible to be already validated.

However, I would like to think of any other solution for your case.

**Comment by hadashiA** [comment]
I've come up with a work-around:

```csharp
foreach (var prefab in prefabs)
{
	builder.Register(new ComponentRegistrationBuilder(prefab, prefab.GetType(), Lifetime.Transient));
}
```
