### ISSUE TITLE
Can I use facade pattern on parent lifetime scope?

### ISSUE THREAD

**Issue by o6098** [hadashiA/VContainer#309]
For example, I have a GameLifetimeScope and a PlayerLifetimeScope.
I want to register PlayerFacade.cs on GameLifetimeScope to be used by other system.
but the player system is in the PlayerLifetimeScope which is child of GameLifetimeScope.
I cannot inject the player system to PlayerFacade.cs.
How do I design my system to use the facade pattern?
Thank you.

**Comment by Artein** [comment]
@o6098, You already have a problem defining PlayerFacade lower in hierarchy than it should be. Following the naming, PlayerFacade must be registered in PlayerLifetimeScope, and will be accessible in that and following scopes.

IMO, you messed up with architecture layers. GameLifetimeScope is about critical "whole-game" systems (serialization, saves, networking etc). Player is a system that lives higher in hierarchy.
