### ISSUE TITLE
Backward compatibility is broken

### ISSUE THREAD

**Issue by longbombus** [hadashiA/VContainer#339]
I had own RegistrationBuilder, so I used an implementation of IRegistration. But in 1.10 this interface is removed, I can use Registration class in my purposes, but it fails due to internal constructor.

**Comment by hadashiA** [comment]
@longbombus I've just merged in a fix to make registration's constructor public.
Is there any other changes I need to make for customization? Thanks

**Comment by longbombus** [comment]
Thank you. This should work now.
