### ISSUE TITLE
Modify or disable LifetimeScope template. (or its encoding and line endings)

### ISSUE THREAD

**Issue by DasOhmoff** [hadashiA/VContainer#350]
Hello 👋, thank you for this plug-in, it is very helpful.

When creating a lifetime scope file. It automatically generates the template for this file. The main issue is its encoding, which is not suited for our project. We need UTF-8 BOM with CRLF line endings. In regards to that, how can I do one of the following things:
1. how can I change the encoding of the template file that gets generated?
2. how can I modify the template file that gets generated?
3. how can I disable this template from getting generated?

It would be nice to have some options in regards to that. For example there could be a checkbox in the VContainerSettings ScriptableObject which allows to disable this template from being generated.

Thank you for your support.

**Comment by hadashiA** [comment]
In #335, An option for this purpose has been added.
