### ISSUE TITLE
Register ".WithParameter" also for fields and properties.

### ISSUE THREAD

**Issue by DasOhmoff** [hadashiA/VContainer#351]
Hello, thank you for your help :)

When registering through the builder, one can use the `.WithParameter` method to specify certain parameters in the constructor that get injected. It would be nice if there would also be something similar for fields and properties.

For example:
```
//register
builder.Register<FieldGameInfo>(Lifetime.Scoped).WithParameter(gameObject.transform);
```
```
//resolve
public class FieldGameInfo
{
    [Inject] public readonly Transform FieldTransform; //Inject into here
}
```

**Comment by hadashiA** [comment]
This issue was fixed.
