### ISSUE TITLE
Instantiate game object by using ".WithParameter".

### ISSUE THREAD

**Issue by DasOhmoff** [hadashiA/VContainer#352]
When registering through the builder, one can use the `.WithParameter` method to specify certain parameters in the constructor that get injected. It would be nice if there would also be something similar for instantiating game objects.

For example:
```
//extension method signature
public static TObject InstantiateWithParameters<TObject, TArg1>              (this IObjectResolver resolver, TObject prefab, TArg1 arg1                        ) where TObject : Object
public static TObject InstantiateWithParameters<TObject, TArg1, TArg2>       (this IObjectResolver resolver, TObject prefab, TArg1 arg1, TArg2 arg2            ) where TObject : Object
public static TObject InstantiateWithParameters<TObject, TArg1, TArg2, TArg3>(this IObjectResolver resolver, TObject prefab, TArg1 arg1, TArg2 arg2, TArg3 arg3) where TObject : Object
```
```
//instantiate
objectResolver.InstantiateWithParameters(prefab, valueA);
```

I tried implementing it myself, but I am not sure how to do so. How could this be done?

Thank you :)

**Comment by YegorStepanov** [comment]
I'm not tested it, but similar code (for plain c# types only) works fine.

```C#
public static TComponent InstantiatePrefab<TComponent, TParam>(this IObjectResolver resolver, TComponent prefab, TParam parameter) where TComponent : Component
{
    var registrationBuilder = new ComponentRegistrationBuilder(prefab, typeof(TComponent), Lifetime.Transient);
    registrationBuilder.WithParameter(parameter);

    Registration registration = registrationBuilder.Build();
    return (TComponent)resolver.Resolve(registration);
}
```

The problem is `ComponentRegistrationBuilder` ctors are internal, so you should modify source code or use reflection to get access to them. 

Simply copying the class won't work either, as it uses internal types.

**Comment by hadashiA** [comment]
There are a number of requests similar to this, but I am reluctant to make them.
I understand the case for wanting to Instantiate by dynamic arguments. But that's not DI, is it?   Dependency injection and parameters are different.
