### ISSUE TITLE
Add AsSelf() to RegisterEntryPoint

### ISSUE THREAD

**Issue by pxlpug** [hadashiA/VContainer#364]
I would like to request the addition of adding AsSelf to the RegisterEntryPoint method. I often create debug classes that wrap my entry point classes. Currently only the interfaces are bound.

**Comment by hadashiA** [comment]
It's easy to implement, but it's actually not very reluctant.

I thought EntryPoint was like a controller in a web application. During execution, "something like a controller" cannot be controlled by any other object. Therefore, I think it is an exceptional to inject EntryPoint to others.

However, as I imagine from your use case, adding a decorator-like feature may be useful 🤔
