### ISSUE TITLE
Dark theme of documentation website breaks benchmark graphs

### ISSUE THREAD

**Issue by GabLeRoux** [hadashiA/VContainer#378]
Dark theme:

![CleanShot 2022-05-06 at 13 16 24@2x](https://user-images.githubusercontent.com/1264761/167180970-7154f1f1-6c61-473b-9e47-56a9c3bb4c9d.png)

Light theme:
![image](https://user-images.githubusercontent.com/1264761/167180804-77872e12-605a-4e06-b2b2-4b7869e03fe6.png)

This can be solved by implementing dark theme with `nivo/bar` and docusaurus `useColorMode`:  
https://docusaurus.io/docs/next/api/themes/configuration#use-color-mode

Or we could simply add a white background to the components :)

Related components:

* https://github.com/hadashiA/VContainer/blob/master/website/src/components/BenchmarkGraph.tsx
* https://github.com/hadashiA/VContainer/blob/master/website/src/components/CodeSizeGraph.tsx
* https://github.com/hadashiA/VContainer/blob/master/website/src/components/GCAllocGraph.tsx

Related docs pages:

* https://github.com/hadashiA/VContainer/blob/master/website/docs/about/what-is-vcontainer.mdx

**Comment by hadashiA** [comment]
Thanks for the report. Fixed in #386.
