### ISSUE TITLE
InjectAttribute is missing [MeansImplicitUse]

### ISSUE THREAD

**Issue by YegorStepanov** [hadashiA/VContainer#381]
Is there a reason why `[Inject]` is not marked with `[MeansImplicitUse]`? Zenject does it.

At least in Rider, the user should use `[Inject, UsedImplicitly]` every time. 

Unity employee [said](https://forum.unity.com/threads/embedded-jetbrains-annotations-in-v5-unityengine-dll.304819/#post-1990523): "you can rely on the [JetBrains] attributes being included in all future versions of Unity".

If you ever want to make a pure .NET version, you can do this:
```C#
#if UNITY_2018_4_OR_NEWER //the first version supported by VContainer
[JetBrains.Annotations.MeansImplicitUse(ImplicitUseKindFlags.InstantiatedNoFixedConstructorSignature)]
#endif
[AttributeUsage]
class InjectAttribute { ... }
```

**Comment by hadashiA** [comment]
The reason this is not marked: I am not at all keen on turning off IDE warnings with Annotation 😓 
But thanks for the sample code!  I'm going to adopt this.
