### ISSUE TITLE
No disposal order?

### ISSUE THREAD

**Issue by YegorStepanov** [hadashiA/VContainer#382]
#### This looks like incorrect behaviour:

![image](https://user-images.githubusercontent.com/19392641/167791734-3d33be11-ee88-40f4-8454-e0cd4d9d6840.png)
`(Forgot to remove Background/Addressables prefixes on the left picture)`

Scope graph is:
```
Project (Root) ---> Bootstrap ---> Game & Menu
```

As I see:
1) `Project` is always disposed first, but should be last.
2) `Bootstrap` should be disposed after it child.
3) `Game` and `Menu` are siblings, it'd be nice to have a deterministic order. They are created one by one with awaiting scene loading:
```C#
using(EnqueueParent(bootstrapScope))
{
    var gameScene = await Load();
    var menuScene = await Load();
}
```

##### The behaviour should be deterministic and 'child-first'.

**Comment by hadashiA** [comment]
> 1. Project is always disposed first, but should be last.

Agree. This is incorrect.

Question. Is this run on an editor?
On the editor, I am running Dispose with playModeStateChanged.
https://github.com/hadashiA/VContainer/blob/master/VContainer/Assets/VContainer/Runtime/Unity/VContainerSettings.cs#L75
However, on the actual device, we are not explicitly executing Dispose on the RootLifetimeScope, so it is unlikely that it is executed first.

> 3. Game and Menu are siblings, it'd be nice to have a deterministic order. 

This depends on how Unity deletes the scene.
It is intuitively straightforward for me.

**Comment by YegorStepanov** [comment]
I deeply apologize for ignoring.

I'll check player behavior today or tomorrow.

**Comment by YegorStepanov** [comment]
Thanks, it's fixed now. Forgot to close
