### ISSUE TITLE
VContainer Diagnostics window

### ISSUE THREAD

**Issue by Yggdrasills** [hadashiA/VContainer#387]
Hey! The problem is that references to already removed dependencies do not disappear in the editor window. For example, you can create a `LifeTimeScope` with one registration and one entry point, which in the constructor accepts the created registration. Run the scene -> remove the `LifeTimeScope` object from the scene (it will call `Dispose` on `OnDestroy`) -> look at the diagnostic window -> dependencies are also present, where it will also be seen that there are links to the created dependencies.

It would be much more convenient if the diagnostic window displayed real-life dependencies at runtime

```
public class DummyScope : LifetimeScope
    {
        protected override void Configure(IContainerBuilder builder)
        {
            builder.Register<DummyModel>(Lifetime.Singleton);
            builder.RegisterEntryPoint<DummyController>();
        }
    }

public class DummyModel
    {
    }

public class DummyController : IInitializable
    {
        private DummyModel _model;

        public DummyController(DummyModel model)
        {
            _model = model;
        }

        public void Initialize()
        {
        }
    }
```

Please add a Refresh button next to the Reload button which will list only existing dependencies

**Comment by hadashiA** [comment]
Perhaps it was solved in #568.
If there is a problem, please reopen.
