### ISSUE TITLE
ECS

### ISSUE THREAD

**Issue by muveso** [hadashiA/VContainer#389]
I don't want to use vcontainer and ecs together but VCONTAINER_ECS_INTEGRATION flag automatically added. It's very frustrating and full of bugs. why doesn't it ask me for permission before adding such a feature?

and also;

Library\PackageCache\jp.hadashikick.vcontainer@1.11.0\Runtime\Unity\InstanceProviders\WorldInstanceProvider.cs(32,44): error CS0117: 'ScriptBehaviourUpdateOrder' does not contain a definition for 'UpdatePlayerLoop'

proper solution smt like that:

```
ScriptBehaviourUpdateOrder.RemoveWorldFromCurrentPlayerLoop(world);
var playerLoop = PlayerLoop.GetCurrentPlayerLoop();
ScriptBehaviourUpdateOrder.AppendWorldToPlayerLoop(world, ref playerLoop);
```

**Comment by hadashiA** [comment]
Fixed in #391.  
It would be great if you could let me know if the problem has been fixed since this fix was merge in. Thanks.
