### ISSUE TITLE
Sporadic resolving issues - instantiated prefab with own LifetimeScope can't find global instance of a class from VContainerSettings.

### ISSUE THREAD

**Issue by akoolenbourke** [hadashiA/VContainer#392]
We are evaluating VContainer and I am experiencing a hard to replicate issue that occasionally results in an exception in VContainer, complaining that there's a certain class not registered and so it can't inject. My setup:

- I have a VContainerCsettings with a derived LifetimeScope that just registers a single class.

- We have a [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)] function that instantiates a global prefab that we put into DontDestroyOnLoad - this prefab has its own LifetimeScope so it can get injections of the class registered in the VContaineSettings Lifetimescope.

- The prefab uses [Inject] on MonoBehaviour member variables (not method injection)

Sometimes the error appears when trying to configure the one in the DDOL prefab, complaining it can't find the global VContainerSettings one.

By rights, it should always be loaded and ready to go but I wonder if the [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)] (Which VContainerSettings uses) compelte in some way.

If I do some log output, when the error occurs I see

1. My BeforeSceneLoad function logs something at the top
2. It instantiates the prefab and the error happens
3. Next the Configure for my global (VContainerSettings) is setup.

When the error doesn't happen, the 2nd and 3rd steps are exchanged which is how it should be.

Obviously that last step is happening too late, so the second step cannot find it. Additionally it seems if I quit Unity and run it again the error will happen immediately, first time so I assume there's some caching going on somewhere (Unity, VContainer??) that means the order changes.

What is the recommended way around this? Would changing the ScriptExecutionOrder help, or should there be some config added to VContainer so it automatically handles this? 

Thanks

**Comment by hadashiA** [comment]
I think the mixed way of initializing instances with VContainer and RuntimeInitializeOnLoadMethod is causing the problem.

Why not unify these with VContainer?
Specifically, we can set the instance to be DontDestroyOnLoad in the root LifetimeScope's Configure.

**Comment by CamAlta** [comment]
We're also having a lot of issues with reliably getting vContainer to initialize correctly and reliably before other code runs when pressing play in editor and in builds.

**Comment by hadashiA** [comment]
I would like to know if #418 would be a fix for this problem. 🤔

**Comment by hadashiA** [comment]
> Would love to know what actually instantiates the root lifetime scope from the vContainerSettings scriptable object 

`Instantiate` means to make an object appear on the scene.
In the current implementation, RootLifetimeScope does not depend on any scene (nor on DontDestroyOnLoad).
The role of the LifetimeScope is to be set up by C# and to hold the serialized values. I intend LifetimeScope itself to be like a ScriptableObject.

Perhaps one solution to the initialization problem is Instantiate, but I think the scene dependency creates another problem.

**Comment by hadashiA** [comment]
If the problems not solved in #418, please reopen this issue.
