### ISSUE TITLE
Test Resource Prefabs with Missing Scripts Causing Warnings on Build

### ISSUE THREAD

**Issue by Soren025** [hadashiA/VContainer#394]
When building, I get the following warnings.

![Console Warnings](https://puu.sh/J6iWt/d10e8b9a56.png)

I tracked it down to the prefabs `ParentChildRelationship` and `ParentChildRelationshipInvalid` in the `VContainer` package folder `/Tests/Resources`.

It does not break anything, It's more an annoyance.

**Comment by hadashiA** [comment]
The cause is as follows

- Test's scripts are separated by asmdef
- But there is no way to exclude Resources/ assets.

Could you please let me know if there is a better way?

Well, but I decided to simply remove the tests that use Resources/.  (#395 )
