### ISSUE TITLE
`VContainer.Unity.PlayerLoopHelper.Dispatch` throwing `NullReferenceException`

### ISSUE THREAD

**Issue by chika-chang** [hadashiA/VContainer#397]
### Description

1. Create unity project and add VContainer package
2. Create a prefab with `LifetimeScope` component
3. Create `VContainer Settings` and set root lifetime scope with previously created prefab
4. Create new scene and add game object with `LifetimeScope` component
5. Enter play mode
6. Exit play mode

### Expected Behaviour

All clean, everything is happy.

### Current Behaviour

Unity console shown as follows:

```
NullReferenceException: Object reference not set to an instance of an object
VContainer.Unity.PlayerLoopHelper.Dispatch (VContainer.Unity.PlayerLoopTiming timing, VContainer.Unity.IPlayerLoopItem item) (at Library/PackageCache/jp.hadashikick.vcontainer@1.11.1/Runtime/Unity/PlayerLoopHelper.cs:149)
VContainer.Unity.VContainerSettings.OnApplicationQuit () (at Library/PackageCache/jp.hadashikick.vcontainer@1.11.1/Runtime/Unity/VContainerSettings.cs:84)
UnityEngine.Application.Internal_ApplicationQuit () (at <4a31731933e0419ca5a995305014ad37>:0)
```

### Environment

- VContainer 1.11.1
- Unity 2021.3.5f1
- Windows 11 21H2

**Comment by hadashiA** [comment]
Fixed in #400
