### ISSUE TITLE
Incorrect\inconsistent tag in 1.11.1 release

### ISSUE THREAD

**Issue by Optifun** [hadashiA/VContainer#399]
There is a typo in README.md in the downlad links.
```json
"jp.hadashikick.vcontainer": "https://github.com/hadashiA/VContainer.git?path=VContainer/Assets/VContainer#1.11.1"
```
Last release tag is "v1.11.1", not "1.11.1".

**Comment by hadashiA** [comment]
I re-created the Tag. Thanks for pointing it out.
https://github.com/hadashiA/VContainer/releases/tag/1.11.1
