### ISSUE TITLE
Build time reflection errors

### ISSUE THREAD

**Issue by WoLfulus** [hadashiA/VContainer#407]
I'm having issues similar to #187 , but with Unity.Input assemblies.

For some reason when trying to make a build, it fails with FileLoadException, but the stack trace is empty. 

The current setup I have is an asmdef that references VContainer, VContainer.CodeGen and Unity.InputSystem.

The class giving trouble is asking VContainer to inject an scriptable object reference (the new input system actions mapping asset).
This is registered in the lifetime scope correctly and works inside the editor.

![image](https://user-images.githubusercontent.com/412397/185485110-c80f060d-ceb5-4760-b2f6-e761e77cfe56.png)

---

I narrowed the problem down to these calls:

https://github.com/hadashiA/VContainer/blob/46ab7c3f4ba02c824a02b08cdd09693077a0a8c7/VContainer/Assets/VContainer/Editor/CodeGen/InjectionILGenerator.cs#L209-L212

Which I'm assuming fails at `module.ImportReference` calls.

I couldn't debug it further since I have no knowledge of Cecil to know exactly was supposed to be done here. The same assemblies/types works on the editor, and I could log the calls and see it went through.

**Comment by hadashiA** [comment]
IL CodeGen is now deperecated. Instead, please try the new feature that uses source generator. https://vcontainer.hadashikick.jp/optimization/source-generator

I don't have enough information to resolve the ImportReference issue and don't have much hope that it will be resolved. Sorry. 🙏
