### ISSUE TITLE
Migration from IL code generation to C# Source Generator

### ISSUE THREAD

**Issue by hadashiA** [hadashiA/VContainer#417]
IL generation has the following downsides:

- Build problems are difficult to investigate, fix and maintain.
    - The IL code itself is understandable.
    - However, it is difficult to understand the Unity build system and the behavior of Mono.Cecil.

If possible I would like to migrate to C# Source Generator.
refs: https://docs.unity3d.com/Manual/roslyn-analyzers.html

**Comment by rekrutacje-unity-vox** [comment]
What is the status of SourceGenerators support?

**Comment by slimshader** [comment]
Hey, what is the status of this one?

**Comment by vangogih** [comment]
@slimshader has already merged to the master https://github.com/hadashiA/VContainer/pull/429
🎉 🎉 🎉

**Comment by hadashiA** [comment]
Thanks for following.
