### ISSUE TITLE
登録済みのインスタンスを破棄して新しく生成したい / Replacing a registered instance with a new one

### ISSUE THREAD

**Issue by BustlingBeaver** [hadashiA/VContainer#427]
@hadashiA 

※ English can be found further down

依存オブジェクトを下記のようにRootLifetimeScopeに登録しています。
```c#
builder.Register<FooModel>(Lifetime.Singleton);
```
MVPパターンを使用しています。設計としては、ViewとPresenterはシーンがロードされる際に必ず初期化したいですので、各シーンのLifetimeScopeにて登録してLifetimeはScopedにしています。
一方、Modelは任意的に初期化するか否かを指定できるような設計にしたいがために、上記のようにRootLifetimeScopeにて登録しています。
しかし、実現するには**登録したインスタンスを破棄して新しく生成したい**と考えていますが、そのような機能が備わっていないように思いました。（勘違いでしたらご指摘いただけますと幸いです）

こちらのIssue(#241)にも記載あるように、以前にReplace機能の案が浮上したようです。このような機能があれば（未実装の認識です）大変便利そうですが、実装予定はありますでしょうか。
それとも、既存の実装で実現可能でしょうか。 

拙いながらも既存の実装で自分なりに考えたところ、以下のようなFactoryを使用すれば似たようなことが実現できていますが、
コード量が増える他、あまりキレイではない気がしますので、最適とは言い難いです。

```c#
// RootLifetimeScope.cs

builder.Register<FooModelWrapper>(Lifetime.Singleton);
builder.RegisterFactory<bool, FooModel>(container =>
{
    // 引数のboolはモデルを初期化するかどうかを意味している
    // falseは既存のインスタンスを、trueは新規インスタンスを返す
    return flag =>
    {
        var wrapper = container.Resolve<FooModelWrapper>();
        
        if (flag || wrapper.Model is null)
            wrapper.Model = new FooModel();
        
        // Modelに注入要素があるため予めやっておく
        container.Inject(wrapper.Model);

        return wrapper.Model;
    };
}, Lifetime.Singleton);

// 他中略...
```

```c#
// FooModel.cs
public class FooModel : IFooModel
{
    [Inject] IHoge someProperty { get; set; }
    // 他中略...
}

public class FooModelWrapper
{
    public FooModel Model { get; set; }
}
```

```c#
// FooPresenter.cs
public class FooPresenter<FooView, FooModel> : IStartable
{
    FooModel Model { get; }
    FooView  View  { get; }

    public Presenter(FooView view, Func<bool, FooModel> modelFactory)
    {
        View  = view;
        // Factoryを呼び出して既存のインスタンスか新しいインスタンスかのどちらかをフラグの値に応じて取得している
        // Hoge.Instance.IsUseNewModelはシーンをロードする際に指定の値を設定する想定
        Model = modelFactory(Hoge.Instance.IsUseNewModel);
    }

    // 他中略...
}
```
VContainerの使い方や把握はまだ浅薄なため間違った認識などがあるかと思いますが、
ご教授・ご検討いただけますと一ユーザとして大変嬉しく存じます。

ここまでお読みくださいましてありがとうございます。:bow:

※ 以下にて英語

=============================================================== 

I am registering my dependency in RootLifetimeScope as follows.
```c#
builder.Register<FooModel>(Lifetime.Singleton);
```
I am using the MVP pattern. Since I would like to initialize the View and Presenter each time a scene is loaded, I have registered them in each scene’s LifetimeScope and set the Lifetime to Scoped.
On the other hand, I want to be able to designate in my code whether to initialize the Model or not. That is why I have registered it in RootLifetimeScope as above.

In order to do that, I would like to **destroy the registered object and replace it with a new one**. However, it seems to me that such a feature has yet to be implemented (please correct me if I am mistaken).
A replace feature has been considered previously, as can be seen in this issue (#241). Such a feature would be most nifty, but do you have any plans of implementing it?

Although I am not fully versed in VContainer and its use, I was able to replicate a similar functionality through the use of a factory.
However, I am not entirely pleased with it, as the amount of code increases and it does not feel like the cleanest solution.

```c#
// RootLifetimeScope.cs

builder.Register<FooModelWrapper>(Lifetime.Singleton);
builder.RegisterFactory<bool, FooModel>(container =>
{
    // The bool argument is a flag for whether or not to initialize the model
    // false means use the current instance, true means create a new instance
    return flag =>
    {
        var wrapper = container.Resolve<FooModelWrapper>();
        
        if (flag || wrapper.Model is null)
            wrapper.Model = new FooModel();
        
        // Model contains things to Inject, so do that here
        container.Inject(wrapper.Model);

        return wrapper.Model;
    };
}, Lifetime.Singleton);

// other registrations...
```

```c#
// FooModel.cs
public class FooModel : IFooModel
{
    [Inject] IHoge someProperty { get; set; }
    // other code...
}

public class FooModelWrapper
{
    public FooModel Model { get; set; }
}
```

```c#
// FooPresenter.cs
public class FooPresenter<FooView, FooModel> : IStartable
{
    FooModel Model { get; }
    FooView  View  { get; }

    public Presenter(FooView view, Func<bool, FooModel> modelFactory)
    {
        View  = view;
        // Call the factory and retrieve either the current instance or a new one based on the flag passed in
        // Hoge.Instance.IsUseNewModel is set with a designated value each time a scene is loaded
        Model = modelFactory(Hoge.Instance.IsUseNewModel);
    }

    // other stuff...
}
```
My knowledge of VContainer and its uses are still highly limited, so I fear I may have used it inappropriately in some way or other.
As an avid user, I would greatly appreciate it if you could provide instruction regarding / consider the implementation of the replace feature. 

Thank you for your time. 🙇

**Comment by hadashiA** [comment]
実現したいことがあまりよくわかりませんでした。

> Modelは任意的に初期化するか否かを指定できる

アプリケーションのロジックによって動的にModelが初期化(あるいは生成)される のであれば、
それがいつどのように実行されるかは DI の設定で制御されるべきものではなく、アプリケーションロジックで制御されるべきだと考えます。

たとえば 
- Model は常にインスタンス化されるが、必要になるまで自身で初期化が遅延されるとか
- DI によるインスタンス化は 必要になるまで遅延されるので、Model を参照するオブジェクトいなければ初期化されないというメカニズムに乗るとか
- あるいは Model を利用する側が 明示的に初期化を呼び出すとか

といった方向を検討されてはいかがでしょうか。(ユースケースを十分に理解できていなかったらすみません)

> Factoryを使用すれば似たようなことが実現

ちなみに、ラムダ式を使った Factory は 、いちいちクラス定義を不要にするための ショートハンドのようなものなので、似たような登録を何度も行うようであれば、ジェネリックスクラスのFactoryを自身で定義してごく普通にRegisterすると煩雑さはなくなるかと思います。

**Comment by BustlingBeaver** [comment]
ご返信くださいましてありがとうございます。:grin:

やはり、私の理解不足や設計に基付いた問題のように思います。（文章だけでは掴みきれず申し訳ありません。具体例などがあれば理解が捗りそうですが、用意するのは大変と承知しています:sweat:）

少し補足しますと、モデルを初期化したい意図（ユースケース）としては、直近のモデルの状態を復活させたかったのです。
これにより、状態をキープしたまま前の画面に「戻る」ことが実現できると期待していました。
「戻る」以外の時は単に遷移するだけよさそうですので、その場合はモデルを初期化すればいいと考えていました。

ただ考え直すと、モデルのインスタンス自体でなくても、モデルに渡すデータを制御できれば実質的に復活（または初期化）が可能になりそうです。
それにしても、設計として何だかんだ言って難がありそうですので、もう少し練っておきたいところです。:thinking:

書いてくださった内容についていくつか質問・コメントがあります。

> あるいは Model を利用する側が 明示的に初期化を呼び出すとか

この文章で想定されている初期化というのは、それぞれのModelにInitializeのようなメソッドが用意されており、利用する側で実行しておくことでフィールドやプロパティに初期値を設定することを意味していますでしょうか。
左様であれば、Model毎に作る必要が出てきて、量が多そうです。そのためDI側で初期化（古いインスタンスの破棄と新しいインスタンスの生成）を任せないかと思い付きましたが、そもそもDIの使い方として間違っているのでしょうか。
それとも、そのような意味ではないのであれば、恐縮ですが詳しくお聞かせいただけますでしょうか。

> •もうすこし DI の枠組みを使いたいのであれば、スコープの動的な生成/破棄をつかうとか

スコープによる動的な生成/破棄の知識に疎いのですが、それなりに考えた結果、使用が難しいと判断しました。
なぜなら、シーンAという単体のシーンで「戻る」ボタンを押下してシーンBという別の単体シーンを復活するにはBがAの子（またはその逆、つまりAがBの子）である必要があるかなと思いましたが、単体シーンなのでそのような関係性がありません。
無理やりAとBを関係付けても、シーンCからでもシーンBを復活したい場合もあるかもしれません。
循環的な依存が起きてしまいそうですので、使用が難しいと判断しましたが、そのような理解は合っていますでしょうか。

> 「初期化されないインスタンスを登録」することに意味を感じないので、必要な場合のみ 解決&破棄されることを考えてはいかがでしょう。

こちらの解決＆破棄については、[Container API](https://vcontainer.hadashikick.jp/resolving/container-api) とスコープをうまく使おうねという風に読み取れましたが、その認識で問題ありませんか。

> ちなみに、ラムダ式を使った Factory は 、いちいちクラス定義を不要にするための ショートハンドのようなものなので、似たような登録を何度も行うようであれば、ジェネリックスクラスのFactoryを自身で定義してごく普通にRegisterすると煩雑さはなくなるかと思います。

ご指摘くださいましてありがとうございます。とても感謝しております。:bow:

最後ですが、本件とこちらのIssue([#241](https://github.com/hadashiA/VContainer/issues/241))と、しようとしていることがそもそも異なるのでしょうか。改めてお聞きしたいですが、後者の方の実装予定はあるのでしょうか。

**Comment by SimonNordon4** [comment]
I had the same issue but came to the conclusion that "Re-injection" goes against DI Principles. Injection happens at the constructor level, and should have all required dependencies at construction.

Once you start "Re-injecting" objects, you're moving away from Dependency Injection. You should either make the dependencies mutable and reset them manually, or create new objects with new dependencies.

**Comment by BustlingBeaver** [comment]
@SimonNordon4 
Thank you for your input! It is most appreciated.

After considering the matter further, I settled upon reconstructing the model (creating it anew) for each scene rather than trying to "re-inject" it, as that seemed the simpler and more practical choice.
