### ISSUE TITLE
Unity VContainer Constructor Injection can't release memory when destory LifetimeScope

### ISSUE THREAD

**Issue by twice7713** [hadashiA/VContainer#433]
I follow this web basic example,but when i change my scene( destory LifetimeScope ),Can't release inject class.

https://vcontainer.hadashikick.jp/resolving/constructor-injection#suppressing-warnings

and use Property Inject can release

What do I need to notice for Constructor Injection?

**Comment by hadashiA** [comment]
@twice7713 Hello. In specification, there seems to be no difference between constructor-injection and field-injection as to release memory, I think.

> Can't release inject class.

Does this means that it keeps being referenced from somewhere?
Do you know the owner of the references ? 
( If possible, it would be helpful if you could provide a simple repro code. 
Thanks.

**Comment by twice7713** [comment]
lifetimescope regist
     builder.RegisterEntryPoint<RuleLoading>(Lifetime.Scoped);
     builder.Register<INeedInitializeWhenStart, SyncDeadreckoning>(Lifetime.Scoped).AsImplementedInterfaces().AsSelf();
     
     can't release SyncDeadreckoning

**Comment by hadashiA** [comment]
@twice7713 You mean the "memory release" is call ~SyncDeadreckoning() ?

This is finalizer. https://learn.microsoft.com/ja-jp/dotnet/csharp/programming-guide/classes-and-structs/finalizers

Unlike c++ destructors, you have no control over when c# finalizers are called.
Consider using `IDisposable` if you want to do explicit post-processing. VContainer calls Dispose() when the container is destroyed.
