### ISSUE TITLE
Container.Resolve<> fails even though I can see the object in the diagnostics window.

### ISSUE THREAD

**Issue by matt-seaton** [hadashiA/VContainer#437]
I created an object with 

builder.RegisterEntryPoint<GameLogic>()

I can see the GameLogic object in the diagnostics window.  Tick and Start are firing.

But I cannot resolve the object to call functions on it. 

Container.Resolve<GameLogic>() throws an VContainerException, no such object of type...

I wasn't sure RegisterEntryPoint was enough to actually create the object, so I tried doing a RegisterInstance before that.  I can then resolve the object later in the code.  But when I set variables on it, they don't take.  In the Tick() function they have reverted to their default values.  What am I missing here

**Comment by hadashiA** [comment]
You can use `RegisterEntryPoint<GameLogic>.AsSelf()`

By default, EntryPoints are not referenced by concrete types.

( The reason for this is that it is simpler to design the entry-point to act as the starting point of the graph. For example, it is not usual to write a program that references and calls the `main` function from somewhere.
