### ISSUE TITLE
I want to execute the injection from LifetimeScope the fastest.

### ISSUE THREAD

**Issue by KazukiKuriyama** [hadashiA/VContainer#449]
We want to execute the injection from LifetimeScope at the earliest possible time right after the game starts.

Is it common practice to set the highest priority in the [Script Execution Order] and enable AutoRun for LifetimeScope?
Please let me know if there is a better way.

**Comment by IShix-g** [comment]
[LifetimeScope's DefaultExecutionOrder can be found here](https://github.com/hadashiA/VContainer/blob/master/VContainer/Assets/VContainer/Runtime/Unity/LifetimeScope.cs#L9). In most cases, it is not necessary to change the Script Execution Order. This is of course when AutoRun is enabled.

**Comment by KazukiKuriyama** [comment]
@IShix-g 
I see! I did not know that.
Thanks for letting me know!!!
