### ISSUE TITLE
Inject to MonoBehaviour at runtime?

### ISSUE THREAD

**Issue by starock** [hadashiA/VContainer#462]
Hi, I'm new at VContainer.

In my game have alot of GameObject created at runtime.
The component XXX at GameObject is inherit MonoBehaviour.

Here is a gameObject(GameManager) In the scene. 
I registerd it:
[SerializeField]
private GameManager gameManager;
builder.RegisterInstance(gameManager); 
builder.RegisterEntryPoint< MyGame >();

In MyGame.cs, inject works fine.
[Inject] GameManager gameManager;
Debug.Log(gameManager.gameMode);

Now  I want register the component XXX (inherit  MonoBehaviour) which created at runtime.
builder.RegisterComponentInHierarchy<XXX>();   //error  at running game
builder.RegisterComponentOnNewGameObject<XXX>(Lifetime.Scoped);  //not  working

in XXX.cs:
[SerializeField]
private GameManager gameManager;
Debug.Log(gameManager.gameMode); // error, gameManager is Null

How can I do that? Help~~ Thanks!

**Comment by hadashiA** [comment]
By default, automatic injects are not performed on GameObjects that are not managed by a container.

You can use the Auto inject gameobject in the inspector of LifetimeScope.
https://vcontainer.hadashikick.jp/resolving/gameobject-injection
