### ISSUE TITLE
Inject a Service in Editor Mode - ExecuteAlways annotation

### ISSUE THREAD

**Issue by rafaeljpc** [hadashiA/VContainer#464]
I'm implementing a MonoBehavior with a simple Service injected that goes to a webservice and get some data.
I wanted that the execution runs at Editor time, with the MonoBehavior annotated with ExecuteAlways and OnValidate implemented.
Is it possible with vContainer? I couldn't find a solution at the docs.

**Comment by hadashiA** [comment]
If we want to make DI work in Editor, we would need to create a context separate from the LifetimeScope (MonoBehaviour) of the VContainer.

VContainer does not currently have official support for this, but
In fact, we can do the following:

```csharp
// Such as EditorWindow , EditorTool , etc

var builder = new ContainerBuilder();
var installer = new MyEditorInstaller(this);
installer.Install(builder);

// Hold container, and maybe dispose on window close.
container = builder.Build();
```

```csharp
public class MyEditorInstaller : IInstaller
{
    public void Install(IContainerBuilder builder)
    {
           //  Register your service classes or etc...
    }    
}
```

**Comment by luojunlin1223** [comment]
@hadashiA Thanks for your answer！

**Comment by rafaeljpc** [comment]
Thank you for the answer!
