### ISSUE TITLE
VContainerILPostProcessor throws "Skip IL waving because cannot detect type" warning when trying to use codegen

### ISSUE THREAD

**Issue by tjumma** [hadashiA/VContainer#465]
I'm getting this warning for every type present in my asmdef. The Assembly references VContainer and VContainer.EnableCodeGen. What am I doing wrong? Thank you!

<img width="410" alt="1" src="https://user-images.githubusercontent.com/55762319/212486206-fa8dc533-d617-4878-9227-94b2053da880.png">
<img width="323" alt="image" src="https://user-images.githubusercontent.com/55762319/212486224-d1b5c281-5a2b-4395-9f91-52515a01aa7b.png">

**Comment by tjumma** [comment]
I'm using VContainer 1.12.0 and Unity 2022.2.2f1

**Comment by hadashiA** [comment]
Do you include `ISceneView` in the same assembly?

Perhaps VContainer has tried to get the ISceneView type in the assembly and failing.

Nevertheless, CodeGen should be working, just skipping this type.

--
You may be concerned that the warnings keep lingering.
In fact, IL code gen is very difficult to provide debugging information and I am working on plans to move to SourceGenerator in the near future. I hope you'll give it a try when you release it. thanks.

**Comment by tjumma** [comment]
I do indeed include` ISceneView` in the same assembly. I'm actually getting these warning for all the classes included in the asmdef - it feels like I'm making some rookie mistake when creating an assembly, but don't know what it is. Can the "Root Namespace" setting of the asmdef be empty regardless of the namespaces of the classes in it?

--
I will definitely check the SourceGenerator codegen when it is out!

**Comment by hadashiA** [comment]
IL CodeGen is now deperecated. Instead, please try the source generator: https://vcontainer.hadashikick.jp/optimization/source-generator
