### ISSUE TITLE
I want to inject dynamic arguments into the objects registered in the VContainer.(VContainer に登録しているオブジェクトに動的な引数を注入させたい。)

### ISSUE THREAD

**Issue by itkmaingit** [hadashiA/VContainer#466]
The Issue is written in English at the top. The description is written in Japanese at the bottom.

### Abstract

Question on how to inject dynamic (e.g. int type) arguments through a DI container. Since they are dynamic, I cannot use the VContainer method WithParameter().

### Body

The MVP pattern is used for class design. However, I am using the MVP pattern for objects that are dynamically generated and destroyed.

What I want to do is initialize the data by passing a dynamic id determined by the application logic to the Model, and initialize the View through the Presenter with the data obtained from the Model. Finally, I want the Presenter to have references to the Model and View.

However, as far as I have thought, I think it is difficult to inject dynamic arguments into Model when using VContainer. However, in that case, it is not possible to make the data to be initialized readonly, which is a little worrying for the design. I couldn't think of a good way to use the Factory class either.

How should I implement this? Or should classes that take dynamic arguments not use a DI container?

Here is the first sample code I thought of.

```csharp:SampleLifetimeScope.cs

public sealed class SampleSceneLifeScope : LifetimeScope
  {
    [SerializeField] private SampleView _sampleViewPrefab;

    protected override void Configure(IContainerBuilder builder_)
    {
      builder.Register<SampleModel>(Lifetime.Scoped);
      builder.Register<SamplePresenter>(Lifetime.Scoped);

      builder.RegisterFactory<int, SamplePresenter>() { container =>
      {
        return
        {
          (int id) =>
          {
            // Instantiate the view here.
            var view = container.Instantiate(_sampleViewPrefab);

            // I don't know how to pass view to Presenter here and id to Model using constructor injection...

            // var presenter = container.Resolve<SamplePresenter>();
            // presenter.Initialize(id, view);
          }
        }
      }}
    }
}
```

I apologize for my poor English. Is there a way to successfully create a factory class? I would be grateful if you could help us.

### 概要

動的な(int 型など)の引数を DI コンテナを通じて注入する方法についての質問です。動的なので、VContainer のメソッドである WithParameter()を使用できません。

### 本論

MVP パターンを使用して設計を行っています。ただ、動的に生成され破棄されるオブジェクトに対し MVP パターンを使用しています。

やりたいこととしては Model に アプリケーションのロジックで決まる動的な id を渡すことでデータの初期化を行い、Model から得られたデータで、Presenter を通し View の初期化も行いたいです。最終的には Presenter が Model と View の参照を持っている形にしたいです。

ただ、私が考えた限りでは VContainer を用いた場合動的な引数を Model に注入することは難しいように思います。別途、Model に Initialize 等のメソッドを実装して、手動で注入することは可能ですがその場合、初期化されるデータを readonly にすることは出来ないのが少し設計として不安です。上手い Factory クラスの使い方も思いつきませんでした。

どのように実装を行えばいいでしょうか。それとも、動的な引数を取るクラスは DI コンテナを用いるべきではないのでしょうか。

以下に最初に考えたサンプルコードを載せておきます。

```csharp:SampleLifetimeScope.cs

public sealed class SampleSceneLifeScope : LifetimeScope
  {
    [SerializeField] private SampleView _sampleViewPrefab;

    protected override void Configure(IContainerBuilder builder_)
    {
      builder.Register<SampleModel>(Lifetime.Scoped);
      builder.Register<SamplePresenter>(Lifetime.Scoped);

      builder.RegisterFactory<int, SamplePresenter>() { container =>
      {
        return
        {
          (int id) =>
          {

            // ここでviewをInstantiateを行います。
            var view = container.Instantiate(_sampleViewPrefab);

            // viewをPresenterに、idをModelにコンストラクタインジェクションを用いて渡す方法が分からないです...
            // var presenter = container.Resolve<SamplePresenter>();
            presenter.Initialize(id, view);
          }
        }
      }}
    }
}
```

上手くファクトリークラスを作成する方法があるのでしょうか。お力添えいただけると幸いです。

**Comment by hadashiA** [comment]
>  // viewをPresenterに、idをModelにコンストラクタインジェクションを用いて渡す方法が分からないです...
> // var presenter = container.Resolve<SamplePresenter>();

現状は、Resolve時に追加の引数を渡すことはサポートしていません。
( そうした機能を入れることに積極的ではない考え方を取っています)

書いていただいたサンプルのやりかたに則るのであれば、愚直にコンストラクタを呼ぶ方法があると思います。

```csharp
// ここでviewをInstantiateを行います。
var view = container.Instantiate(_sampleViewPrefab);

var dependency1 = contaienr.Resolve<Dependency1>();  // もし追加の依存があるなら手動で取得
var dependency2 = contaienr.Resolve<Dependency2>();

return new SamplePresenter(view, dependency1, dependency2); // など
```

コンストラクトインジェクションは上記↑のような処理を自動化しているに過ぎません。
( もし コンストラクタの引数が多過ぎて面倒な場合は 、それはそれでリファクタリング対象ではないかなと考えてます)

また、以下は 一般論としてのMVPについての見解です。

- 一般論としては、presenterについては、viewやmodelよりも長く安定した寿命を持つ静的な存在にできるのではないかと思います。
    - presenter はあくまで model や view を仲介するものとしての責任のみを持たせれば、それ自身には動的な状態は必要なく、model や view あるいはそれらのファクトリやリポジトリなどを持たせるだけで十分ではないかと思います。
    - 状態ではなく機能のみを持つオブジェクトは、動的な状態がなくても初期化可能なので、 スコープ(LifetimeScope) やシーンと同様のある程度長い寿命を持たせることができます。
    - その場合、上記のようなDIの設定に持ち込むロジックは単純になるのではないかとおもいます。

参考になれば。

**Comment by itkmaingit** [comment]
返信ありがとうございます。通知を見逃していました。

> 一般論としては、presenterについては、viewやmodelよりも長く安定した寿命を持つ静的な存在にできるのではないかと思います。

その通りだと思います。それらを踏まえ、愚直にコンストラクタを呼ぶ方法をとりつつリファクタリングしていこうと思います。
