### ISSUE TITLE
I need advice

### ISSUE THREAD

**Issue by GMassta** [hadashiA/VContainer#475]
Hi, i have a question. How heavy LifeTimeScope? 
I want to use VContainer in mobile project, its need a hight speed code. Is it normal practice to use "scope" often (every game character has self scope), or be best to use it only global (managers, controllers...)? Or one scope on one scene ? 
Maby any recommendations? 
Thanks.

**Comment by hadashiA** [comment]
@GMassta 

In my opinion, scope is supposed to be one for each context to some extent, such as a "scene" in a game, or a "map", "field", "area", and so on.

Creating one scope per game charactor is too granular.

I understand that game characters are created dynamically at runtime, but it is too much to leave all dynamically created instances to the DI.
Instead, Factory/Provider and other "functions" that generate instances at runtime may be DI.

( The concept of scope is essentially equivalent to that used in the HTTP server framework.
In the HTTP server, one scope is started for each request/reply.

**Comment by GMassta** [comment]
@hadashiA thank you
I read you documentation again and understood this
