### ISSUE TITLE
Microsoft.CodeAnalysis error in 1.13.0

### ISSUE THREAD

**Issue by tigana0210** [hadashiA/VContainer#477]
Tried SourceGenerator in 1.13.0 and got this error, how can I fix it?

Assembly 'Assets/VContainer.SourceGenerator.dll' will not be loaded due to errors:
Unable to resolve reference 'Microsoft.CodeAnalysis'. Is the assembly missing or incompatible with the current platform?

**Comment by hadashiA** [comment]
@tigana0210 

Are you following these steps?
- https://vcontainer.hadashikick.jp/optimization/source-generator#how-to-enable-vcontainer-source-generator
- https://docs.unity3d.com/Manual/roslyn-analyzers.html

This dll should have the `RoslynAnalyzer` label.
Also, my documentation seems to be missing the following steps: This may also be required.

> Go to Select platforms for plugin and disable Any Platform.
> Go to Include Platforms and disable Editor and Standalone.

If you still get an error after checking the above, could you tell me your Unity version?

**Comment by tigana0210** [comment]
> > Go to Select platforms for plugin and disable Any Platform.
> > Go to Include Platforms and disable Editor and Standalone.

It's fixed after these two steps were done (Standalone can be left enabled though), thank you.

**Comment by hadashiA** [comment]
Sounds good :) Thank you for confirmation.
