### ISSUE TITLE
Virtual generated methods (Mono.Cecil) not supported in IL2CPP

### ISSUE THREAD

**Issue by ooonush** [hadashiA/VContainer#486]
If a type has virtual methods generated using Mono.Cecil, the game crashes when injecting into that type in the IL2CPP build.

This happens in the foreach loop when methodInfo is a generated method. The game crashes when methodInfo.IsDefined(typeof(InjectAttribute), true) is called.

Here is an example from script 212 TypeAnalyser.cs:
```cs
foreach (var methodInfo in type.GetRuntimeMethods())
{
    // Here, if there is a generated method, the game crashes
    if (methodInfo.IsDefined(typeof(InjectAttribute), true))
    {
        // do...
    }
}
```
This is most likely due to a compilation error. When generating the IsDefined virtual method, it starts an infinite recursion because the inherit parameter = true. This can be fixed by not using IsDefined, but writing the attribute check method yourself. Zenject has done this, so there is no such error there.

**Comment by hadashiA** [comment]
Probably resolved in 505.
Also, Mono.Cecil is deprecated and SouceGenerator is recommended, so we will Close.
