### ISSUE TITLE
Delegate registration impossible for Value Types

### ISSUE THREAD

**Issue by slimshader** [hadashiA/VContainer#489]
Hi,

I need to register a type that has to be accessed from another object by its getter so I have to use delegate registration (resolve + getter access) but it has generic constraint of a "class". Is there a reason for it? Other registration types do not have this limitation.
```
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static RegistrationBuilder Register<TInterface>(
            this IContainerBuilder builder,
            Func<IObjectResolver, TInterface> implementationConfiguration,
            Lifetime lifetime)
            where TInterface : class
            => builder.Register(new FuncRegistrationBuilder(implementationConfiguration, typeof(TInterface), lifetime));
```

**Comment by hadashiA** [comment]
Ah, ok.
That's right. There is no consistency in this, and it's probably a mistake. I'll fix it.

**Comment by slimshader** [comment]
> 

Great, what is the eta on that?
