### ISSUE TITLE
A typo in the documents?

### ISSUE THREAD

**Issue by shiena** [hadashiA/VContainer#49]
I think the argument is also a concrete type because it registers a concrete type.
    
````diff
diff --git a/README.md b/README.md
index 955667e..5231ebe 100644
--- a/README.md
+++ b/README.md
@@ -436,7 +436,7 @@ It can resolve like this:
 ```csharp
 class ClassA
 {
-    public ClassA(IServiceA serviceA) { /* ... */ }
+    public ClassA(ServiceA serviceA) { /* ... */ }
 }
 ```
````

**Comment by hadashiA** [comment]
As you say this is a mistake  :sweat_smile:
Thank you for pointing out!

Fixed: https://github.com/hadashiA/VContainer/commit/2fa38366461078114f2b01d1ff79f1e07f42a321
