### ISSUE TITLE
Throwing DC0061 error when install entities package

### ISSUE THREAD

**Issue by chikacc** [hadashiA/VContainer#494]
### Description

1. Create unity project and add VContainer package
2. Install Entities 1.0.0-pre.65

### Expected Behaviour

All clean, everything is happy.

### Current Behaviour

Unity console shown as follows:

```
Assets\VContainer\Runtime\Annotations\IAsyncStartable.cs(13,1): error DC0061: Assembly VContainer relies on Unity.Entities which uses the Unity.Collections AllocatorHandle type but does not have a reference to Unity.Collections.  Please add an assembly reference to `Unity.Collections` in the asmdef for VContainer.
```

### Environment

- Entities 1.0.0-pre.65
- VContainer 1.13.1
- Unity 2023.2.0a7
- Windows 11 22H2

**Comment by nicloay** [comment]
I have the same issue. thanks for the PR. hope it will be merged soon. for now, I use git reference in the manifest.json with this fix.
