### ISSUE TITLE
[Advice] Best practice for DI usage on objects which derive from each other 

### ISSUE THREAD

**Issue by bmgoncu** [hadashiA/VContainer#496]
Hi folks,

Me and our team were wondering on the best practice of doing DI on objects which derive from each other.
Let us give an example;

```
public class A : MonoBehaviour
{
     [Inject]
     private void Inject(Dep1, Dep2)
     { ... }
}
```
```
public class B : A
{
     [Inject]
     private void Inject(Dep3, Dep4)
     { ... }
}
```
currently this causes issues on 1.13  (thats not the issue btw), but how should we tackle a situation like this? Whats the best practice there?

The same can be asked for Non-MonoBehaviour classes;
```
public class A
{
     [Inject]
     public A(Dep1, Dep2)
     { ... }
}
```
```
public class B : A
{
     [Inject]
     public B(Dep1, Dep2, Dep3, Dep4) : base(Dep1, Dep2)
     { ... }
}
```
How should we tackle this?

Please advice

**Comment by ooonush** [comment]
Hi! This problem occurs with inheritance, and yes, this bug appeared in version 1.13.1. Inherited methods are called several times for each subtype in the inheritance hierarchy (even if there is no override modifier). Hopefully this will be fixed in the next update.
