### ISSUE TITLE
フィールド代入処理最適化の提案

### ISSUE THREAD

**Issue by kraiHD** [hadashiA/VContainer#5]
Unityには、`FieldInfo.SetValue`と同一の処理を数倍高速に実行できる `UnsafeUtility.CopyObjectAddressToPtr` という機能があります。
もし可能であれば、利用してみるのはいかがでしょうか？

例えば、このように使います。このコードの `UnsafeFieldInfo.SetValue` が `FieldInfo.SetValue` よりも高速になることをご確認ください。
```
readonly struct UnsafeFieldInfo {
	public readonly Type fieldType;
	readonly int offset;

	public UnsafeFieldInfo(FieldInfo fieldInfo) {
		fieldType = fieldInfo.FieldType;
		offset = UnsafeUtility.GetFieldOffset(fieldInfo);
	}

	public unsafe void SetValue(object target, object value) {
		if (target == null) { return; }
		var targetPtr = UnsafeUtility.PinGCObjectAndGetAddress(target, out ulong targetHandle);
		UnsafeUtility.CopyObjectAddressToPtr(value, (byte*)targetPtr + offset);
		UnsafeUtility.ReleaseGCObject(targetHandle);
	}
}
```

なお、PropertyInfoにはこの方法は使えないと思われます。

**Comment by hadashiA** [comment]
UnsafeUtility かなり興味深かったのですが、以下の理由から 利用を見送ろうとおもいます。

- どちらかというと フィールドインジェクションよりもコンストラクタインジェクションが推奨なので 、フィールドだけの改善の優先度があまり高くない
- 純粋なコンテナ部分は UnityEngineに依存しないつくりになっているので 可能ならそれは維持したい
- ILコード生成モード が実装されたので、その場合の C# の setter ベタ書きは おそらくあまり有意差がない

提案ありがとうございます、 Unity の独自機能についてはあまり詳しくないのでウォッチしていきたいです。

**Comment by kraiHD** [comment]
そうですね、IL生成が実装された時点でこれをする意味は薄くなったと私も思います。返信ありがとうございます！
