### ISSUE TITLE
Exclude Attribute-Inheriting Classes from Source Generation

### ISSUE THREAD

**Issue by chikacc** [hadashiA/VContainer#502]
### Please describe the feature you would like to see implemented:

I would like to request a feature to exclude classes that inherit from Attribute in the Source Generator. This feature would allow users to avoid unnecessary code generation for classes that are not intended for dependency injection.

### Describe the solution you'd like:

Modify the Source Generator to include a check for classes that inherit from Attribute and exclude them from the generation process. This can be achieved by iterating through the classes and checking their inheritance chain to identify those that inherit from Attribute.

Example:

```cs
foreach (var classSymbol in compilation.GetSymbols())
{
    if (!InheritsFromAttribute(classSymbol))
    {
        // Proceed with code generation
    }
}

bool InheritsFromAttribute(INamedTypeSymbol classSymbol)
{
    while (classSymbol != null)
    {
        if (classSymbol.Name == nameof(Attribute))
        {
            return true;
        }
        classSymbol = classSymbol.BaseType;
    }
    return false;
}
```

### Describe alternatives you've considered:

An alternative solution could involve using an attribute (e.g., [VContainerExclude]) on specific classes to manually exclude them from the code generation process. However, this approach requires additional manual work from users and may not be as efficient as automatically excluding classes inheriting from Attribute.

**Comment by hadashiA** [comment]
@chikacc Thanks for the suggestion.

In #510, a change was made to exclude Attribute.

You can also exclude a class by adding `[InjectIgnore]` to the class definition.
This was an undocumented feature, but is now documented in #511.
