### ISSUE TITLE
Missing reference to Unity.Collections after installing Entities 1.0.0-pre.65 on Unity 2022.2.14

### ISSUE THREAD

**Issue by NeistH2o** [hadashiA/VContainer#503]
I'm having issues after installing Entities which may not be related to VContainer, but one of the errors I get says this:
![image](https://user-images.githubusercontent.com/25915415/232257857-bed8dd71-ed85-4674-9c49-07d0eef991f8.png)

**Comment by NeistH2o** [comment]
I just tried editing the asmdef of the package in my IDE, even though I'm not supposed to, and it does seem to have allowed the compilation to continue.

**Comment by hadashiA** [comment]
Seems duplicates of #494

**Comment by NeistH2o** [comment]
It would be nice to have this change released because the import problem keeps appearing, I just updated a different package and now I can't get it to work. Adding the missing reference manually works once and then breaks down again after an assembly reload.
