### ISSUE TITLE
`WhenInjectedInto` analog

### ISSUE THREAD

**Issue by arewerage** [hadashiA/VContainer#517]
Hi. Is there an analog to the `WhenInjectedInto` function from Zenject?

**Comment by hadashiA** [comment]
I am not positive about implementing the logic of such a DI setup.

Perhaps what we want to do is similar to `.WithParameter`.

Or lambda expressions are flexible enough. It would be good to create extensions for each project.

```csharp
builder.Register<IA>(container =>) 
{
    var b = new B();
    return new A(b);
});
````
