### ISSUE TITLE
SourceGenerator Error

### ISSUE THREAD

**Issue by zhuxianzhiniko** [hadashiA/VContainer#518]
Hi, after I use [Inject] for Field Injection, SourceGenerator will have a reference exception.

After I tested, I found that this error will appear as long as I use namespace. If I remove the namespace, SourceGenerator can work normally.

Log:
Container.SourceGenerator\VContainer.SourceGenerator.VContainerSourceGenerator\TestGeneratedInjector.g.cs(18,39): error CS0246: The type or namespace name 'TestNamespace' could not be found (are you missing a using directive or an assembly reference? )

VContainer :1.13.2
Unity: 2022.2.19f1

This is a minimal case
[VContainerTest.zip](https://github.com/hadashiA/VContainer/files/11528001/VContainerTest.zip)

**Comment by zhuxianzhiniko** [comment]
I found that it can be easily fixed.

Just modify VContainerSourceGenerator.cs, line 222

fieldSymbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

**Comment by hadashiA** [comment]
Fixed in #532. Thanks for the report.
