### ISSUE TITLE
Roslyn Source Generator Compiler Error

### ISSUE THREAD

**Issue by luojunlin1223** [hadashiA/VContainer#522]
Hi, I am using Vcontainer, Messagepipe and UniTask as working base. After I imported Roslyn Source Generator, I got this error:
<img width="452" alt="1684753081129-afb295d9-b8f5-46c6-86ae-b9aec0d8dcc3" src="https://github.com/hadashiA/VContainer/assets/63366848/da624f54-515c-46ab-b89d-b79c8b5f3d89">

Has anyone got the same error message? This looks to be related to Messagepipe.

**Comment by luojunlin1223** [comment]
<img width="702" alt="image" src="https://github.com/hadashiA/VContainer/assets/63366848/5f6c51ce-bbf8-4172-a979-ea2bbc8fa5a4">
<img width="701" alt="image" src="https://github.com/hadashiA/VContainer/assets/63366848/5a863ff5-1be5-4651-b845-0f2e8cb217b9">
<img width="669" alt="image" src="https://github.com/hadashiA/VContainer/assets/63366848/45730444-0046-4cc5-9210-5c656fc04c31">
<img width="634" alt="image" src="https://github.com/hadashiA/VContainer/assets/63366848/321751c4-e0b6-4f98-ad18-cda953939aac">

**Comment by hadashiA** [comment]
@luojunlin1223  This was fixed in v1.13.1 (#480 ). Please reopen if the problem still persists.
