### ISSUE TITLE
Saving prefab error caused by builder.RegisterComponentInNewPrefab()

### ISSUE THREAD

**Issue by carolinetis** [hadashiA/VContainer#523]
Hi!!

I am using VContainer in my Unity project to instantiate a prefab from a package.
I have a script in my project (actually, from another package) that calls UnityEditor.AssetDatabase.SaveAssets().

When I use the builder.RegisterComponentInNewPrefab() method to instantiate the prefab and SaveAssets() gets called, I get this error: Saving Prefab to immutable folder is not allowed.

My guess is that it is trying to save the prefab in the package.

In the end I solved the issue by defining how the prefab should be instantiated [using delegate](https://vcontainer.hadashikick.jp/registering/register-using-delegate) , but I still wanted to raise the issue.

Thanks for all your work 😃

**Comment by hadashiA** [comment]
As far as I know, the API to create a prefab from a GameObject is PrefabUtility.
https://docs.unity3d.com/ScriptReference/PrefabUtility.SaveAsPrefabAsset.html

Or, maybe the error is a location issue.

VContainer is for runtime dependency resolution, and VContainer itself probably doesn't do anything to interfere with AssetDatabase behavior.
If you still think there might be a problem on the VContainer side, please provide sample code and error logs. 🙏
