### ISSUE TITLE
Please support Container.Instantiate<class>()

### ISSUE THREAD

**Issue by GaLeGayGay** [hadashiA/VContainer#54]
sorry my english,i use google translate

This sometimes happens in projects. I need to create a class and inject property, and assign the class to a local variable.
That's all I can do now.
```
    public class A
    {
        [Inject] private string B;
        public A()
        {
            
        }  
    }

    public class B
    {
        public B()
        {
            var C = new A();
            xxx.Inject(C);
            C........
        }
    }
```

I would like to have a method similar to the Instantiate method in Zenject.
That way I can put variables in the constructor. And it would be much smoother to write

**Comment by hadashiA** [comment]
@GaLeGayGay Hello.
From 1.3.0, Container.Inject etc. are supported. Please confirm.
https://github.com/hadashiA/VContainer#use-container-directory
