### ISSUE TITLE
does it have a signalBus feature like zenject?

### ISSUE THREAD

**Issue by virtouso** [hadashiA/VContainer#545]
i need to know is there a event dispatcher or signalbus with this container.  i want to migrate from zenject to VContainer. is there any similar feature for that?

**Comment by YegorStepanov** [comment]
![image](https://github.com/hadashiA/VContainer/assets/19392641/6b51d7cd-e55b-4758-9319-86f109c7e7a0)

from here: https://vcontainer.hadashikick.jp/comparing/comparing-to-zenject

**Comment by slimshader** [comment]
Use [MessagePipe](https://github.com/Cysharp/MessagePipe) which is superior to Zenject signales and has VContainter integration. Better yet, consider if you REALLY need signals/message que in your design.

**Comment by slimshader** [comment]
> I simply install IObservables and use UniRx

the only thing in UniRx that resembles Signals is IMessageBus, Rx is fantastic technolory but best for handling event streams not to integrate components (like injectable signales or event bus)

**Comment by hadashiA** [comment]
There are various paradigms for messaging systems, and the policy is not to build them into the DI container.

**Comment by virtouso** [comment]
i also figured out that unity has a builtin EventBus that works in same way as zenject signalBus. its always better to use builtin tools instead of bunch of plugins.

**Comment by hadashiA** [comment]
:memo:.
The following are some of the libraries that integrate well with VContainer.
- https://github.com/hadashiA/VitalRouter
- https://github.com/Cysharp/MessagePipe
