### ISSUE TITLE
Publish Nuget package

### ISSUE THREAD

**Issue by yaron-E92** [hadashiA/VContainer#549]
As part of my CI I need to be able to retrieve at least VContainer and VContainer.Unity.
Could you please publish a Nuget package with at least the relevant dlls for these namespaces?
I could also do it myself if you give me permission

**Comment by hadashiA** [comment]
For `VContainer.Unity`, it may not be possible to pass the compilation through the nuget environment.

For Unity-independent parts, there may be advantages.
So it could be done, however, I have my doubts about the need for a DI container in a test environment, so it is a low priority.

However, I hope to support Microsfot.Extensions.DependencyInjection abstract layer in the near future.
Depending on the nature of this work, we may end up exposing VContainer in the nuget package.
However, we have not yet designed the details. 

I would like to discuss this in #639.
