### ISSUE TITLE
[Unity] Is there a way to check if SourceGenerator is working?

### ISSUE THREAD

**Issue by lamlnt** [hadashiA/VContainer#583]
I added the SourceGen dll into the project but I still see ILPostProcessorErrorException and Skip IL waving warnings when building for android. Does this mean SourceGen is incorrectly set up?

**Comment by hadashiA** [comment]
> see ILPostProcessorErrorException and Skip IL waving warnings 

I believe this is from the CodeGen feature (using mono-cecil) prior to the introduction of the source generator.
In v1.14.0, the old CodeGen was removed. So the warning should no longer appear.

Also, if Souce Generator is running, you can check the generated code from the IDE.
