### ISSUE TITLE
Separate Scriptable Object installer

### ISSUE THREAD

**Issue by dre0dru** [hadashiA/VContainer#59]
Hello! I am trying to create separate installer for `ScriptableObject` for `RootLifetimeScope` in `VContainerSettings`.
The way I am doing it is this:
```
 public class ScriptableObjectsInstaller : ScriptableObject, IInstaller
    {
        [SerializeField]
        private EncryptionSettings _encryptionSettings;

        public void Install(IContainerBuilder builder)
        {
            builder.RegisterInstance<AuthenticationStorage>(new AuthenticationStorage(_encryptionSettings));
        }
    }
```

And then in `RootLifetimeScope`:
```
 public class RootLifetimeScope : LifetimeScope
    {
        [SerializeField]
        private ScriptableObjectsInstaller _scriptableObjectsInstallers;

        protected override void Configure(IContainerBuilder builder)
        {
             Push(_scriptableObjectsInstallers);
        }
    }
```

The problem is that the method `Install` in `ScriptableObjectsInstaller` seems to be called several times, once for each `LifetimeScope` in scene. E.g. if I have 3 scenes additevely loaded, then it will be called 3 times.

Is it intended behaviour or bug? 
If it's intented, then how to accomplish the behaviour I want? To be clear:
I don't want to bloat `RootLifetimeScope` with tons of references to different  `ScriptableObject`, so I want to group them in separate installers and just "feed" them to `RootLifetimeScope`.

**Comment by dre0dru** [comment]
Ok, I it is pretty easy to achieve begaviour that I want without using `IInstaller`, so the question changes to:
Do I misunderstand the usage of `IInstaller` and `LifetimeScope.Push` method?

**Comment by hadashiA** [comment]
> Do I misunderstand the usage of IInstaller and LifetimeScope.Push method?

Yup. Yeah. LifetimeScope.Push affects the LifetimeScope that is loaded after the Push call. (Usually this is used with the using block). This name may be a little confusing. Maybe I could rename this to something like `BeginXXX ()` in the future.

If you want to apply IInstaller within Configure, you can simply use IInstaller.Install

`` `csharp
_scriptableObjectInstaller.Install (builder)
`` ```
