### ISSUE TITLE
Is VContainer still supported?

### ISSUE THREAD

**Issue by Watcher3056** [hadashiA/VContainer#611]
It seems there is no updates and replies for the half of year

**Comment by hadashiA** [comment]
Sorry for the delay in response.

In the meantime, maintenance is ongoing.

If you look at the history of the master branch, you will see that functionality additions and improvements are continuing.

Lots of contributions have been made, so the next release will be a big one. 
Maybe in the near future.

Incidentally, my new library [VitalRouter](https://github.com/hadashiA/VitalRouter) also has features that depend on VContainer. Check it out.

**Comment by hadashiA** [comment]
For now, I have released version 1.14.0.
