### ISSUE TITLE
RootLifetimeScope registers 2 times when starting a scene

### ISSUE THREAD

**Issue by SipiRaussi** [hadashiA/VContainer#648]
Everything that is registered in RootLifetimeScope gets instantiated 2 times when scene is started. Even when they are registered with `Lifetime.Singleton`

## Context

`TestService` implements `IInitializable` interface
`TestDependency` is bare C# class
`VContainerSettings` is assigned to be preloaded in project settings

Unity version: 2022.3.20f1
VContainer version: 1.15.1

![image](https://github.com/hadashiA/VContainer/assets/32201210/7db64c9e-af80-4132-a9e6-d57da575c1b6)

**Comment by SipiRaussi** [comment]
This doesn't happen in version 1.14

**Comment by hadashiA** [comment]
Hello, thanks for the report.
This problem seems to occur probably only in editor.
I have been fixed in #650.
