### ISSUE TITLE
Add support for ScriptableObject collections

### ISSUE THREAD

**Issue by jarrodspurrier** [hadashiA/VContainer#651]
Currently, you can only register a single instance of a particular ScriptableObject type. Attempting to register multiple instances of the same type will result in a `VContainerException: Conflict implementation type`. I would love to be able to register multiple instances so that I can inject them as collections like everything else via IEnumerable<T> or IReadOnlyList<T>.

**Comment by hadashiA** [comment]
- In my opinion, why not just create a wrapper ScriptableObject with Collection as a property? 
- Also, using anything other than LifetimeSingleton allows duplicate types to be registered. This restriction is probably a bit confusing, but that is the current specification.
