### ISSUE TITLE
VContainer for non-unity usage?

### ISSUE THREAD

**Issue by man-chi** [hadashiA/VContainer#659]
is it suitable to use VContainer for non-unity propose, such as windows native or azure microservice application?

**Comment by hadashiA** [comment]
VContainer is quite Unity-specific in design and provides features that are closely related to Unity. So, outside of Unity, it would be better to use a generic DI library.

In the .NET environment, Microsoft.Extensions.DependencyInjection has taken root as the underlying technology.
Currently, it is probably better to use this as the basis.

refs #639.
