### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by favoyang** [hadashiA/VContainer#67]
Issue: 
- Git tag: 1.3.0
- package.json version: 1.2.1

Solution
- Bump version of package.json
- Re-tag 1.3.0

The issue is detected by https://openupm.com/packages/jp.hadashikick.vcontainer/?subPage=pipelines

**Comment by hadashiA** [comment]
Thank you for the report.
I just fixed the problem in 1.3.0.
https://openupm.com/packages/jp.hadashikick.vcontainer/?subPage=versions

(I probably need to set up CI  :sweat_smile:
