### ISSUE TITLE
Are there any platform restrictions/gotchas?

### ISSUE THREAD

**Issue by boraty14** [hadashiA/VContainer#676]
For cross platform development, is there any restrcitons I should know platform spesific? I searched about it but could not find anything about it.

**Comment by hadashiA** [comment]
It doesn't use any environment-specific features, so it will probably work in most environments.

One thing to note is that in the IL2CPP environment, the constructor may be stripped.
(See https://vcontainer.hadashikick.jp/resolving/constructor-injection

I haven't tested it exhaustively, though,
It appears to work on iOS, Android, WebGL, Steam and NIntendo Switch.

If you're having problems in a particular environment, let me know.
