### ISSUE TITLE
Compilation error on Unity2021.3.0~Unity2021.3.17.

### ISSUE THREAD

**Issue by Akeit0** [hadashiA/VContainer#690]
FindAnyObjectByType was added in version 2021.3.18 so it causes a compilation error in versions 2021.3.0~2021.3.17.
https://github.com/hadashiA/VContainer/blob/892c490c6a7f97dd564e933a1dbb50293e6fd093/VContainer/Assets/VContainer/Runtime/Unity/LifetimeScope.cs#L118-L125

**Comment by hadashiA** [comment]
The specification of the directive is very messy. Apologies. I will scrutinise it.
