### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by favoyang** [hadashiA/VContainer#7]
Git tag: 0.2.0
package.json's version: 0.0.1

To fix: bump version, then re-tag 0.2.0.

To avoid it in the future, recommended readings:
- Managing release with CLI https://medium.com/openupm/how-to-maintain-upm-package-part-4-managing-package-release-with-cli-972ff5311163
- Managing release with CI: https://medium.com/openupm/how-to-maintain-upm-package-part-2-f352fbf5f87c

----
The issue is detected by [openupm](https://openupm.com/packages/jp.hadashikick.vcontainer/) build pipelines (right bottom "build issues" section). OpenUPM is an open-source UPM registry with automatic build pipelines.

**Comment by hadashiA** [comment]
Oh... It's my mistake.
Thank you for your feedback and telling me about opemupm and CI operations !

I will try to fix and re-release.

**Comment by hadashiA** [comment]
Lates build seems succeeded :)
https://openupm.com/packages/jp.hadashikick.vcontainer/

Thanks!

**Comment by favoyang** [comment]
Cool, the build happens 5-10mins after you create the latest build.
