### ISSUE TITLE
Version number rollback conflicts with others such as MessagePipe

### ISSUE THREAD

**Issue by boraty14** [hadashiA/VContainer#714]
For a reason the latest version udpated from 1.16.3 to 1.6.3. The version numbering conflicts with other such as
MessagePipe requiring min v 1.14.0 for "MESSAGEPIPE_OPENGENERICS_SUPPORT" define.

It is fixable from editor adding scripting  define but still I think would be better to have consistence versioning

**Comment by hadashiA** [comment]
Oh. Sorry, I must have made a mistake trying to release 1.16.3.
I created the latest release with the tag 1.16.4 again.
Thanks for the report.

https://github.com/hadashiA/VContainer/releases/tag/1.16.4
