### ISSUE TITLE
How to register Open Generic type with factory method

### ISSUE THREAD

**Issue by slimshader** [hadashiA/VContainer#715]
Let's say I have (not purely hypothetical):

```c#
Ilogger<T> LoggerFactory.CreateLogger<T>();
```

and I want objects to be able to inject specific instance of ILogger<T> direclty like so:

```c#
class MyClass
{
   MyClass(Ilogger<MyClass> logger) {}
}
```

docs have "Register Open Generics" section but I see no Register overload that would allow to pass CreateLogger<T> as a factory method to Register(typeof(Ilogger<>)

**Comment by hadashiA** [comment]
Try the following:

```csharp
            var loggerFactory = LoggerFactory.Create(x => x.AddZLoggerUnityDebug());
            builder.RegisterInstance(loggerFactory);
            builder.Register(typeof(Logger<>), Lifetime.Singleton).As(typeof(ILogger<>));
```

 Note:
- It works because `new Logger<T>(ILoggerFactory)` is called by VContainer.

**Comment by slimshader** [comment]
Thanks, this indeed solves this case, but what in general?
