### ISSUE TITLE
Question: When executing as a CustomEditor

### ISSUE THREAD

**Issue by dev-platong** [hadashiA/VContainer#721]
Is there a way to use VContainer in EditMode rather than PlayMode?
Dependencies seem to be registered by Containers added to the scene, but when executing from a CustomEditor, dependency resolution fails and results in an error.

The translation maintains the technical terms (CustomEditor, PlayMode, EditMode, VContainer, Container) as they are commonly used in English programming contexts.

**Comment by hadashiA** [comment]
Manually using `new ContainerBuilder()`, containers can be used anywhere in a scene-independent manner.

Please refer to this answer as well.
https://github.com/hadashiA/VContainer/issues/464#issuecomment-1418462821
