### ISSUE TITLE
IStartable.Start() が例外で繰り返し実行される / Unexpected Repeated Execution of IStartable.Start()

### ISSUE THREAD

**Issue by tobyapi** [hadashiA/VContainer#729]
再現環境:
- Unity 2022.3.43f1
- VContainer v1.16.6

以下のコードを適当な GameObject にアタッチして実行すると、`IStartable.Start()` が何度も実行されていました。この挙動が想定通りかお伺いしたいです。

```cs
using System;
using VContainer;
using VContainer.Unity;

public class TestLifetimeScope : LifetimeScope
{
    protected override void Configure(IContainerBuilder builder)
    {
        builder.Register<TestClass>(Lifetime.Singleton).AsImplementedInterfaces();
    }
}

public class TestClass : IStartable
{
    void IStartable.Start()
    {
        throw new Exception();
    }
}
```
![13](https://github.com/user-attachments/assets/7420a0d0-1ae3-441b-8dcc-1c98a39d73ef)

---

When the following code is attached to an appropriate GameObject and executed, IStartable.Start() was being called repeatedly. I would like to ask if this behavior is as expected.

**Comment by hadashiA** [comment]
報告ありがとうございます。
これは期待する挙動ではないですね..

問題は、内部的に例外を投げっぱなしにしているために、後処理が動いてないことのようです。
ここでの例外は、アプリケーション側で catch する方法がないため、例外を投げっぱなしにするのは止めて、デフォルトでエラーを単にログに出す挙動に変更することにしました。

#734 で修正しました。
