### ISSUE TITLE
VCON0008: The [Inject] does not have accessible to set from the same dll. It cannot support to inject by the source generator.

### ISSUE THREAD

**Issue by wintbiit** [hadashiA/VContainer#735]
## Environment
Unity version: 6000.0.30f1
VContainer version: 1.16.6 (Installed from openupm, with soruce generator from release page)
OS: macos15 silicon

Source generator plugin is installed correctly
![image](https://github.com/user-attachments/assets/671f719d-62f7-46f0-b432-f5928d60d692)

Asmdef already referenced VContainer
![image](https://github.com/user-attachments/assets/00624beb-f615-4e2b-8124-395143c13790)

## Issue
Simply declare a class like
```csharp
    public class TimeSystem : ITimeSystem, IFixedTickable
    {
        [Inject] internal ICommandPublisher Publisher { get; set; }
        [Inject] internal IPerformanceSystem PerformanceSystem { get; set; }
        [Inject] internal NetworkManager NetworkManager { get; set; }
        [Inject] internal ICacheProvider<double> DoubleCacheBox { get; set; }
        [Inject] internal ICacheProvider<JudgeSystemStage> JudgeSystemStageCacheBox { get; set; }
    }
```

Then rider and unity prints warning:
> VCON0008: The [Inject] 'Publisher' does not have accessible to set from the same dll. It cannot support to inject by the source generator

Changing `internal` to `public` won't help

## Question
What's the correct way of using `[Inject]` with source generator?

**Comment by RedGlow** [comment]
Could it be the same as my bug? https://github.com/hadashiA/VContainer/issues/730

**Comment by wintbiit** [comment]
> Could it be the same as my bug? https://github.com/hadashiA/VContainer/issues/730

ah yes. Sorry for duplicate issue
