### ISSUE TITLE
[Zenject] (IMemory)Pool support

### ISSUE THREAD

**Issue by MeikelLP** [hadashiA/VContainer#89]
Has this library (or will it have) an alternative to Zenject's IMemoryPool?

It's a question not a feature request. If it's not in this library it's fine because there are plenty libraries for this. I'd love to see this in some kind of "we do not support" section in the docs :)

**Comment by hadashiA** [comment]
Yes, Currently, any object pool is not embeded.

Object pools are relevant and useful.
However, it seems to me that smart commonality through libraries is not simple, since the requirements of each of our projects are different.

> I'd love to see this in some kind of "we do not support" section in the docs :)

Agree. I would like to consider posting. Thanks!

**Comment by hadashiA** [comment]
Added to Not Supported section. #95
